/* ========================================================================
  YAME: 디지털 예진 운영/레퍼런스 스키마 (MySQL/InnoDB)
  - 규칙: 모든 객체 UPPER_SNAKE_CASE, 키워드 대문자
  - PK 기본 전략: 밀리초 타임스탬프(로그성 테이블) 또는 AUTO_INCREMENT
  - 좌표 규칙: X=경도(LON), Y=위도(LAT), POINT(x,y)
========================================================================= */


/* =========================================================
  1) 운영 핵심 (개인식별 없음)
========================================================= */

-- ----------------------------------------------------------------------
-- SYMPTOM_LOGS: 증상 로그 수집 (익명)
-- ----------------------------------------------------------------------
DROP TABLE IF EXISTS SYMPTOM_LOGS;
CREATE TABLE IF NOT EXISTS SYMPTOM_LOGS (
  LOG_ID            BIGINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '증상 이벤트 고유 ID(자동증가)',
  SYMPTOM_TEXT      TEXT NOT NULL COMMENT '사용자 입력 증상 원문(자유기술 포함)',
  SUB_SYMPTOMS      JSON NULL COMMENT '보조 증상 배열(JSON, 예: ["기침","콧물"])',
  PREDICTED_DISEASE VARCHAR(120) COMMENT 'ML이 추정한 질병 라벨(정규화 키 또는 한글명)',
  RECOMMENDATION    ENUM('PHARMACY','HOSPITAL') NOT NULL COMMENT '권유 분기: 약국(PHARMACY) 또는 병원(HOSPITAL)',
  DRUG_SUGGESTED    VARCHAR(120) COMMENT '추천 OTC 약품명(있을 때만 저장)',
  ITEM_SEQ               VARCHAR(20)  NOT NULL COMMENT '품목 기준코드(DUR)',
  ITEM_NAME              VARCHAR(500) NULL     COMMENT '품목명(DUR)',
  DUR_FLAGS         JSON NULL COMMENT 'DUR 관련 위반/주의 플래그 목록(JSON 배열)',
  REGION_LABEL      VARCHAR(120) COMMENT '주소 라벨(행정구/동 등, 통계용)',
  LONGITUDE         VARCHAR(20) COMMENT '경도',
  LATITUDE          VARCHAR(20) COMMENT '위도',
  GPS_ACCURACY_M    INT NULL COMMENT 'GPS 정확도(미터 단위)',
  CREATED_AT        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집 시각(KST 기준)',
  INDEX IDX_LOGS_CREATED (CREATED_AT) COMMENT '시간순 조회용 색인',
  INDEX IDX_LOGS_RECO (RECOMMENDATION, CREATED_AT) COMMENT '권유타입+시간 복합색인',
  INDEX IDX_LOGS_DISEASE (PREDICTED_DISEASE(64), CREATED_AT) COMMENT '질병별 집계용 색인',
  INDEX IDX_LOGS_REGION (REGION_LABEL(64), CREATED_AT) COMMENT '지역별 통계용 색인'
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='증상 로그(익명 수집, 통계/ML 학습 원천)';




/* =========================================================
  2) 기관/시설 마스터
========================================================= */

-- ----------------------------------------------------------------------
-- HIRA_HOSPITAL_INFO: 심평원 병원 정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS HIRA_HOSPITAL_INFO (
  ID               BIGINT UNSIGNED NOT NULL PRIMARY KEY
                     DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  YKIHO            VARCHAR(500)  NOT NULL COMMENT '요양기관 기호(암호화)',
  YADM_NM          VARCHAR(500) NULL COMMENT '기관명',
  TELNO            VARCHAR(30)  NULL COMMENT '전화번호',
  HOSP_URL         VARCHAR(500) NULL COMMENT '홈페이지 URL',
  CL_CD            VARCHAR(10)  NULL COMMENT '종별 코드',
  CL_CD_NM         VARCHAR(80)  NULL COMMENT '종별 명칭',
  SIDO_CD          VARCHAR(10)  NULL COMMENT '시도 코드',
  SIDO_CD_NM       VARCHAR(50)  NULL COMMENT '시도 명칭',
  SGGU_CD          VARCHAR(10)  NULL COMMENT '시군구 코드',
  SGGU_CD_NM       VARCHAR(50)  NULL COMMENT '시군구 명칭',
  ADDR             VARCHAR(500) NULL COMMENT '주소',
  EMDONG_NM        VARCHAR(80)  NULL COMMENT '읍면동명',
  POST_NO          VARCHAR(10)  NULL COMMENT '우편번호',
  X_POS            DECIMAL(10,7) NULL COMMENT '경도(LON)',
  Y_POS            DECIMAL(10,7) NULL COMMENT '위도(LAT)',
  LOCATION         POINT         NULL COMMENT '좌표 POINT(x,y)',
  DR_TOT_CNT       INT NULL COMMENT '의사 총원',
  MDEPT_GDR_CNT    INT NULL COMMENT '전문의 수',
  MDEPT_INTN_CNT   INT NULL COMMENT '인턴 수',
  MDEPT_RESDNT_CNT INT NULL COMMENT '레지던트 수',
  MDEPT_SDR_CNT    INT NULL COMMENT '기타 의사 수',
  DETY_GDR_CNT     INT NULL COMMENT '치과의사 수',
  DETY_INTN_CNT    INT NULL COMMENT '치과 인턴 수',
  DETY_RESDNT_CNT  INT NULL COMMENT '치과 레지던트 수',
  DETY_SDR_CNT     INT NULL COMMENT '치과 기타 의사 수',
  CMDC_GDR_CNT     INT NULL COMMENT '한의사 수',
  CMDC_INTN_CNT    INT NULL COMMENT '한방 인턴 수',
  CMDC_RESDNT_CNT  INT NULL COMMENT '한방 레지던트 수',
  CMDC_SDR_CNT     INT NULL COMMENT '한방 기타 의사 수',
  PNURS_CNT        INT NULL COMMENT '간호사 수',
  ESTB_DD          CHAR(8)       NULL COMMENT '개설일자 YYYYMMDD',
  DISTANCE         DECIMAL(10,3) NULL COMMENT '거리(질의 시 계산값 저장 가능)',
  CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_HIRA_YKIHO (YKIHO) COMMENT '기관 식별자 유니크',
  KEY IDX_HIRA_NAME (YADM_NM) COMMENT '기관명 색인',
  KEY IDX_HIRA_ADDR (ADDR) COMMENT '주소 색인'
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='심평원 병원 기본정보';

-- ----------------------------------------------------------------------
-- NEMC_EMERGENCY_BASE: 응급의료기관 기본정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS NEMC_EMERGENCY_BASE (
  ID               BIGINT UNSIGNED NOT NULL PRIMARY KEY
                     DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  HPID             VARCHAR(16)  NOT NULL COMMENT '응급기관 ID',
  DUTY_NAME        VARCHAR(500) NULL COMMENT '기관명',
  DUTY_ADDR        VARCHAR(500) NULL COMMENT '주소',
  DUTY_TEL1        VARCHAR(30)  NULL COMMENT '대표전화',
  DUTY_TEL3        VARCHAR(30)  NULL COMMENT '응급실 전화',
  POST_CDN1        VARCHAR(5)   NULL COMMENT '우편번호 앞자리',
  POST_CDN2        VARCHAR(5)   NULL COMMENT '우편번호 뒷자리',
  WGS84_LON        DECIMAL(10,7) NULL COMMENT '경도',
  WGS84_LAT        DECIMAL(10,7) NULL COMMENT '위도',
  LOCATION         POINT         NULL COMMENT '좌표 POINT',
  DUTY_INF         TEXT          NULL COMMENT '기관 안내/소개',
  DUTY_MAPIMG      VARCHAR(500)  NULL COMMENT '지도 이미지 URL',
  DUTY_ERYN        TINYINT       NULL COMMENT '응급실 여부',
  DUTY_HAYN        TINYINT       NULL COMMENT '입원실 여부',
  DUTY_HANO        INT           NULL COMMENT '병상 수',
  HVEC INT NULL COMMENT '뇌혈관센터 가용', 
  HVOC INT NULL COMMENT '심혈관센터 가용', 
  HVCC INT NULL COMMENT '화상센터 가용', 
  HVNCC INT NULL COMMENT '신경과 가용', 
  HVCCC INT NULL COMMENT '중증소아센터 가용', 
  HVICC INT NULL COMMENT '중환자실 가용', 
  HVGC INT NULL COMMENT '외상센터 가용',
  DUTY_TIME1S CHAR(4) NULL COMMENT '월요일 진료시작', DUTY_TIME1C CHAR(4) NULL COMMENT '월요일 진료종료',
  DUTY_TIME2S CHAR(4) NULL COMMENT '화요일 시작',     DUTY_TIME2C CHAR(4) NULL COMMENT '화요일 종료',
  DUTY_TIME3S CHAR(4) NULL COMMENT '수요일 시작',     DUTY_TIME3C CHAR(4) NULL COMMENT '수요일 종료',
  DUTY_TIME4S CHAR(4) NULL COMMENT '목요일 시작',     DUTY_TIME4C CHAR(4) NULL COMMENT '목요일 종료',
  DUTY_TIME5S CHAR(4) NULL COMMENT '금요일 시작',     DUTY_TIME5C CHAR(4) NULL COMMENT '금요일 종료',
  DUTY_TIME6S CHAR(4) NULL COMMENT '토요일 시작',     DUTY_TIME6C CHAR(4) NULL COMMENT '토요일 종료',
  DUTY_TIME7S CHAR(4) NULL COMMENT '일요일 시작',     DUTY_TIME7C CHAR(4) NULL COMMENT '일요일 종료',
  DUTY_TIME8S CHAR(4) NULL COMMENT '공휴일 시작',     DUTY_TIME8C CHAR(4) NULL COMMENT '공휴일 종료',
  M_KIOSK_TY25 ENUM('Y','N') NULL COMMENT '소아응급 구분', 
  M_KIOSK_TY1  ENUM('Y','N') NULL COMMENT '뇌출혈', 
  M_KIOSK_TY2  ENUM('Y','N') NULL COMMENT '뇌경색', 
  M_KIOSK_TY3  ENUM('Y','N') NULL COMMENT '심근경색', 
  M_KIOSK_TY4  ENUM('Y','N') NULL COMMENT '중증외상', 
  M_KIOSK_TY5  ENUM('Y','N') NULL COMMENT '화상', 
  M_KIOSK_TY6  ENUM('Y','N') NULL COMMENT '정신', 
  M_KIOSK_TY7  ENUM('Y','N') NULL COMMENT '중증', 
  M_KIOSK_TY8  ENUM('Y','N') NULL COMMENT '소아', 
  M_KIOSK_TY9  ENUM('Y','N') NULL COMMENT '분만', 
  M_KIOSK_TY10 ENUM('Y','N') NULL COMMENT '고압산소', 
  M_KIOSK_TY11 ENUM('Y','N') NULL COMMENT '기타',
  DGID_ID_NAME TEXT NULL COMMENT '진료과/센터 상세',
  HPBDN INT NULL COMMENT '분만실', HPCCUYN INT NULL COMMENT '흉부외과 중환자', HPCUYN INT NULL COMMENT '중환자실', HPERYN INT NULL COMMENT '응급실', 
  HPGRYN INT NULL COMMENT '입원실', HPICUYN INT NULL COMMENT '신생아중환자', HPNICUYN INT NULL COMMENT '소아중환자', HPOPYN INT NULL COMMENT '수술실',
  HIRA_YKIHO       VARCHAR(500) NULL COMMENT '심평원 YKIHO FK',
  CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_NEMC_EM_HPID (HPID) COMMENT '응급기관 고유 ID',
  KEY IDX_NEMC_EM_NAME (DUTY_NAME) COMMENT '기관명 색인',
  KEY IDX_NEMC_EM_ADDR (DUTY_ADDR) COMMENT '주소 색인',
  KEY IDX_NEMC_EM_HIRA (HIRA_YKIHO) COMMENT '심평원 YKIHO 색인',
  CONSTRAINT FK_NEMC_EM_TO_HIRA FOREIGN KEY (HIRA_YKIHO)
    REFERENCES HIRA_HOSPITAL_INFO(YKIHO)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='응급의료기관 기본정보 (NEMC API)';

-- ----------------------------------------------------------------------
-- NEMC_TRAUMA_BASE: 외상센터 기본정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS NEMC_TRAUMA_BASE (
  ID               BIGINT UNSIGNED NOT NULL PRIMARY KEY
                     DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  HPID             VARCHAR(16)  NOT NULL COMMENT '외상센터 ID',
  DUTY_NAME        VARCHAR(500) NULL COMMENT '센터명',
  DUTY_ADDR        VARCHAR(500) NULL COMMENT '주소',
  DUTY_TEL1        VARCHAR(30)  NULL COMMENT '대표전화',
  DUTY_TEL3        VARCHAR(30)  NULL COMMENT '응급실 전화',
  POST_CDN1        VARCHAR(5)   NULL COMMENT '우편번호 앞자리',
  POST_CDN2        VARCHAR(5)   NULL COMMENT '우편번호 뒷자리',
  WGS84_LON        DECIMAL(10,7) NULL COMMENT '경도',
  WGS84_LAT        DECIMAL(10,7) NULL COMMENT '위도',
  LOCATION         POINT         NULL COMMENT '좌표 POINT',
  DUTY_INF         TEXT          NULL COMMENT '센터 안내',
  DUTY_MAPIMG      VARCHAR(500)  NULL COMMENT '지도 이미지 URL',
  DUTY_ERYN        TINYINT       NULL COMMENT '응급실 여부',
  DUTY_HAYN        TINYINT       NULL COMMENT '입원실 여부',
  DUTY_HANO        INT           NULL COMMENT '병상 수',
  HVEC INT NULL COMMENT '뇌혈관 가용', HVOC INT NULL COMMENT '심혈관 가용', HVCC INT NULL COMMENT '화상 가용',
  HVNCC INT NULL COMMENT '신경과 가용', HVCCC INT NULL COMMENT '중증소아 가용', HVICC INT NULL COMMENT 'ICU 가용', H_VGC INT NULL COMMENT '외상센터 가용',
  DUTY_TIME1S CHAR(4) NULL COMMENT '월 시작', DUTY_TIME1C CHAR(4) NULL COMMENT '월 종료',
  DUTY_TIME2S CHAR(4) NULL COMMENT '화 시작', DUTY_TIME2C CHAR(4) NULL COMMENT '화 종료',
  DUTY_TIME3S CHAR(4) NULL COMMENT '수 시작', DUTY_TIME3C CHAR(4) NULL COMMENT '수 종료',
  DUTY_TIME4S CHAR(4) NULL COMMENT '목 시작', DUTY_TIME4C CHAR(4) NULL COMMENT '목 종료',
  DUTY_TIME5S CHAR(4) NULL COMMENT '금 시작', DUTY_TIME5C CHAR(4) NULL COMMENT '금 종료',
  DUTY_TIME6S CHAR(4) NULL COMMENT '토 시작', DUTY_TIME6C CHAR(4) NULL COMMENT '토 종료',
  DUTY_TIME7S CHAR(4) NULL COMMENT '일 시작', DUTY_TIME7C CHAR(4) NULL COMMENT '일 종료',
  DUTY_TIME8S CHAR(4) NULL COMMENT '공휴일 시작', DUTY_TIME8C CHAR(4) NULL COMMENT '공휴일 종료',
  M_KIOSK_TY25 ENUM('Y','N') NULL COMMENT '소아응급', 
  M_KIOSK_TY1  ENUM('Y','N') NULL COMMENT '뇌출혈', 
  M_KIOSK_TY2  ENUM('Y','N') NULL COMMENT '뇌경색', 
  M_KIOSK_TY3  ENUM('Y','N') NULL COMMENT '심근경색', 
  M_KIOSK_TY4  ENUM('Y','N') NULL COMMENT '중증외상', 
  M_KIOSK_TY5  ENUM('Y','N') NULL COMMENT '화상', 
  M_KIOSK_TY6  ENUM('Y','N') NULL COMMENT '정신', 
  M_KIOSK_TY7  ENUM('Y','N') NULL COMMENT '중증', 
  M_KIOSK_TY8  ENUM('Y','N') NULL COMMENT '소아', 
  M_KIOSK_TY9  ENUM('Y','N') NULL COMMENT '분만', 
  M_KIOSK_TY10 ENUM('Y','N') NULL COMMENT '고압산소', 
  M_KIOSK_TY11 ENUM('Y','N') NULL COMMENT '기타',
  DGID_ID_NAME TEXT NULL COMMENT '진료과/센터 상세',
  HPBDN INT NULL COMMENT '분만실', HPCCUYN INT NULL COMMENT '흉부외과 중환자', HPCUYN INT NULL COMMENT '중환자실', HPERYN INT NULL COMMENT '응급실', 
  HPGRYN INT NULL COMMENT '입원실', HPICUYN INT NULL COMMENT '신생아중환자', HPNICUYN INT NULL COMMENT '소아중환자', HPOPYN INT NULL COMMENT '수술실',
  HIRA_YKIHO       VARCHAR(500) NULL COMMENT '심평원 YKIHO FK',
  CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_NEMC_TR_HPID (HPID) COMMENT '외상센터 고유 ID',
  KEY IDX_NEMC_TR_NAME (DUTY_NAME) COMMENT '센터명 색인',
  KEY IDX_NEMC_TR_ADDR (DUTY_ADDR) COMMENT '주소 색인',
  KEY IDX_NEMC_TR_HIRA (HIRA_YKIHO) COMMENT '심평원 YKIHO 색인',
  CONSTRAINT FK_NEMC_TR_TO_HIRA FOREIGN KEY (HIRA_YKIHO)
    REFERENCES HIRA_HOSPITAL_INFO(YKIHO)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='외상센터 기본정보 (NEMC API)';

-- ----------------------------------------------------------------------
-- HIRA_PHARMACY_INFO: 약국 기본정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS HIRA_PHARMACY_INFO (
  ID         BIGINT UNSIGNED NOT NULL PRIMARY KEY
               DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  YKIHO      VARCHAR(500)  NOT NULL COMMENT '요양기관 기호(암호화)',
  YADM_NM    VARCHAR(100) NOT NULL COMMENT '약국명/기관명',
  CL_CD      VARCHAR(2)   NULL COMMENT '종별코드(예: 81)',
  CL_CD_NM   VARCHAR(100) NULL COMMENT '종별 코드명',
  SIDO_CD    VARCHAR(6)   NULL COMMENT '시도코드',
  SIDO_CD_NM VARCHAR(100) NULL COMMENT '시도명',
  SGGU_CD    VARCHAR(6)   NULL COMMENT '시군구코드',
  SGGU_CD_NM VARCHAR(100) NULL COMMENT '시군구명',
  EMDONG_NM  VARCHAR(100) NULL COMMENT '읍면동명',
  POST_NO    VARCHAR(6)   NULL COMMENT '우편번호',
  ADDR       VARCHAR(500) NULL COMMENT '주소',
  TELNO      VARCHAR(50)  NULL COMMENT '전화번호',
  ESTB_DD    CHAR(8)      NULL COMMENT '개설일자(YYYYMMDD 원문)',
  X_POS      DECIMAL(16,13) NULL COMMENT '경도(LON, 소수 13)',
  Y_POS      DECIMAL(16,13) NULL COMMENT '위도(LAT, 소수 13)',
  LOCATION   POINT          NULL COMMENT '좌표 POINT(x,y)',
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_PHARM_YKIHO (YKIHO) COMMENT '약국 식별자 유니크',
  KEY IDX_PHARM_NAME (YADM_NM) COMMENT '약국명 색인',
  KEY IDX_PHARM_ADDR (ADDR) COMMENT '주소 색인'
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COMMENT='약국 기본정보 (HIRA)';




/* =========================================================
   3) DUR 성분 기준 테이블군 — PK를 원문 일련번호(DUR_SEQ)로 통일
   (단, 성분 병용금기는 원문에 일련번호가 없어서 자연키 사용)
========================================================= */

DROP TABLE IF EXISTS DUR_MIX_CONTRAINDICATION;
-- 성분-성분 병용금기: 원문에 개별 일련번호가 없어 (INGR_CODE, MIXTURE_INGR_CODE) 복합 PK 사용
CREATE TABLE DUR_MIX_CONTRAINDICATION (
  TYPE_NAME              VARCHAR(20)   NULL  COMMENT '유형명: 병용금기',
  MIX_TYPE               VARCHAR(20)   NULL  COMMENT '혼합 유형: 단일/복합',
  INGR_CODE              VARCHAR(20)   NOT NULL COMMENT '성분 코드(대상)',
  INGR_ENG_NAME          VARCHAR(500)  NULL  COMMENT '성분명(영문)',
  INGR_KOR_NAME          VARCHAR(500)  NULL  COMMENT '성분명(한글)',
  MIX                    VARCHAR(500)  NULL  COMMENT '혼합 성분 정보(원문)',
  ORI                    TEXT          NULL  COMMENT '원문 제품/제형 목록',
  CLASS                  VARCHAR(500)  NULL  COMMENT '분류 코드/명',
  MIXTURE_MIX_TYPE       VARCHAR(20)   NULL  COMMENT '상대 혼합 유형',
  MIXTURE_INGR_CODE      VARCHAR(20)   NOT NULL COMMENT '상대 성분 코드',
  MIXTURE_INGR_ENG_NAME  VARCHAR(500)  NULL  COMMENT '상대 성분명(영문)',
  MIXTURE_INGR_KOR_NAME  VARCHAR(500)  NULL  COMMENT '상대 성분명(한글)',
  MIXTURE_MIX            VARCHAR(500)  NULL  COMMENT '상대 혼합 성분 정보',
  MIXTURE_ORI            TEXT          NULL  COMMENT '상대 원문 제품/제형 목록',
  MIXTURE_CLASS          VARCHAR(500)  NULL  COMMENT '상대 분류 코드/명',
  NOTIFICATION_DATE      CHAR(8)       NULL  COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT         TEXT          NULL  COMMENT '금기/주의 내용',
  REMARK                 VARCHAR(500)  NULL  COMMENT '비고',
  DEL_YN                 VARCHAR(10)   NULL  COMMENT '삭제 여부',
  CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (INGR_CODE, MIXTURE_INGR_CODE),               -- 자연키 기반 PK (대칭 A-B/B-A 별개 저장)
  KEY IDX_MIX_INGR (INGR_CODE),
  KEY IDX_MIX_MIXTURE (MIXTURE_INGR_CODE),
  KEY IDX_MIX_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 병용금기(성분 기준, 자연키 PK)';

DROP TABLE IF EXISTS DUR_PREGNANCY_CONTRAINDICATION;
CREATE TABLE DUR_PREGNANCY_CONTRAINDICATION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 임부금기',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형(쉼표 구분)',
  GRADE              VARCHAR(20)   NULL    COMMENT '금기 등급(예: 1등급)',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '금기/주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),                         -- 원문 일련번호를 PK로
  KEY IDX_PREG_INGR (INGR_CODE),
  KEY IDX_PREG_GRADE (GRADE),
  KEY IDX_PREG_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 임부금기(성분 기준)';

DROP TABLE IF EXISTS DUR_DOSE_CAUTION;
CREATE TABLE DUR_DOSE_CAUTION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 용량주의',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형',
  MAX_QTY            VARCHAR(100)  NULL    COMMENT '최대 허용 용량',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_DOSE_INGR (INGR_CODE),
  KEY IDX_DOSE_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 용량주의(성분 기준)';

DROP TABLE IF EXISTS DUR_DURATION_CAUTION;
CREATE TABLE DUR_DURATION_CAUTION (
  DUR_SEQ              BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME            VARCHAR(20)   NULL    COMMENT '유형명: 투여기간주의',
  MIX_TYPE             VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR             TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR             TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME           VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME            VARCHAR(800)  NULL    COMMENT '제형',
  MAX_DOSAGE_TERM      VARCHAR(100)  NULL    COMMENT '최대 투여기간',
  NOTIFICATION_DATE    CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT       TEXT          NULL    COMMENT '주의 내용',
  REMARK               VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN               VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_DUR_INGR (INGR_CODE),
  KEY IDX_DUR_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 투여기간주의(성분 기준)';

DROP TABLE IF EXISTS DUR_ELDERLY_CAUTION;
CREATE TABLE DUR_ELDERLY_CAUTION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 노인주의',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_ELDERLY_INGR (INGR_CODE),
  KEY IDX_ELDERLY_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 노인주의(성분 기준)';

DROP TABLE IF EXISTS DUR_AGE_CONTRAINDICATION;
CREATE TABLE DUR_AGE_CONTRAINDICATION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 특정연령대금기',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '금기/주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  AGE_BASE           VARCHAR(50)   NULL    COMMENT '연령 기준(예: 18세 이하)',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_AGE_INGR (INGR_CODE),
  KEY IDX_AGE_DATE (NOTIFICATION_DATE),
  KEY IDX_AGE_BASE (AGE_BASE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 특정연령대금기(성분 기준)';

DROP TABLE IF EXISTS DUR_THERAPEUTIC_DUPLICATION;
CREATE TABLE DUR_THERAPEUTIC_DUPLICATION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 효능군중복',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  EFFECT_CODE        VARCHAR(500)  NULL    COMMENT '효능군 코드/명',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '금기/주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  SERS_NAME          VARCHAR(500)  NULL    COMMENT '상세 계열/군 명칭',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_DUP_INGR (INGR_CODE),
  KEY IDX_DUP_EFFECT (EFFECT_CODE),
  KEY IDX_DUP_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR: 효능군중복(성분 기준)';

/* =========================================================
   4) DUR 품목 기준 테이블군 — PK: 원문 DUR_SEQ (쌍은 복합PK)
========================================================= */

DROP TABLE IF EXISTS ITEM_MIX_CONTRAINDICATION;
-- 품목 병용금기: 본/상대 행 각각 DUR_SEQ가 존재 → (DUR_SEQ, MIXTURE_DUR_SEQ) 복합 PK
CREATE TABLE ITEM_MIX_CONTRAINDICATION (
  DUR_SEQ                BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(본 행)',
  TYPE_CODE              VARCHAR(200)   NULL     COMMENT '유형 코드(예:A)',
  TYPE_NAME              VARCHAR(20)  NULL     COMMENT '유형명: 병용금기',
  MIX                    VARCHAR(20)  NULL     COMMENT '혼합 유형: 단일/복합',
  INGR_CODE              VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_KOR_NAME          VARCHAR(500) NULL     COMMENT '성분명(한글)',
  INGR_ENG_NAME          VARCHAR(500) NULL     COMMENT '성분명(영문)',
  MIX_INGR               TEXT         NULL     COMMENT '혼합 성분 정보',
  ITEM_SEQ               VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  ITEM_NAME              VARCHAR(500) NULL     COMMENT '품목명',
  ENTP_NAME              VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                  TEXT         NULL     COMMENT '성상',
  FORM_CODE              VARCHAR(20)  NULL     COMMENT '제형 코드',
  ETC_OTC_CODE           VARCHAR(20)  NULL     COMMENT '전문/일반 코드',
  CLASS_CODE             VARCHAR(20)  NULL     COMMENT '분류 코드',
  FORM_NAME              VARCHAR(800) NULL     COMMENT '제형명',
  ETC_OTC_NAME           VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  CLASS_NAME             VARCHAR(500) NULL     COMMENT '분류명',
  MAIN_INGR              VARCHAR(500) NULL     COMMENT '주성분 원문',
  MIXTURE_DUR_SEQ        BIGINT UNSIGNED NOT NULL COMMENT '상대 DUR 일련번호',
  MIXTURE_MIX            VARCHAR(20)  NULL     COMMENT '상대 혼합 유형',
  MIXTURE_INGR_CODE      VARCHAR(20)  NULL     COMMENT '상대 성분 코드',
  MIXTURE_INGR_KOR_NAME  VARCHAR(500) NULL     COMMENT '상대 성분명(한글)',
  MIXTURE_INGR_ENG_NAME  VARCHAR(500) NULL     COMMENT '상대 성분명(영문)',
  MIXTURE_ITEM_SEQ       VARCHAR(20)  NULL     COMMENT '상대 품목 기준코드',
  MIXTURE_ITEM_NAME      VARCHAR(500) NULL     COMMENT '상대 품목명',
  MIXTURE_ENTP_NAME      VARCHAR(500) NULL     COMMENT '상대 제조/수입사명',
  MIXTURE_FORM_CODE      VARCHAR(20)  NULL     COMMENT '상대 제형 코드',
  MIXTURE_ETC_OTC_CODE   VARCHAR(20)  NULL     COMMENT '상대 전문/일반 코드',
  MIXTURE_CLASS_CODE     VARCHAR(20)  NULL     COMMENT '상대 분류 코드',
  MIXTURE_FORM_NAME      VARCHAR(800) NULL     COMMENT '상대 제형명',
  MIXTURE_ETC_OTC_NAME   VARCHAR(20)  NULL     COMMENT '상대 전문/일반 구분명',
  MIXTURE_CLASS_NAME     VARCHAR(500) NULL     COMMENT '상대 분류명',
  MIXTURE_MAIN_INGR      VARCHAR(500) NULL     COMMENT '상대 주성분 원문',
  NOTIFICATION_DATE      CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT         TEXT         NULL     COMMENT '금기/주의 내용',
  REMARK                 VARCHAR(500) NULL     COMMENT '비고',
  ITEM_PERMIT_DATE       VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  MIXTURE_ITEM_PERMIT_DATE VARCHAR(20) NULL    COMMENT '상대 품목 허가일(원문)',
  MIXTURE_CHART          TEXT         NULL     COMMENT '상대 성상',
  CHANGE_DATE            VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  MIXTURE_CHANGE_DATE    VARCHAR(20)  NULL     COMMENT '상대 변경일(원문)',
  BIZRNO                 VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ, ITEM_SEQ, MIXTURE_ITEM_SEQ),      -- 복합 PK
  KEY IDX_ITEM_MIX_ITEM (ITEM_SEQ),
  KEY IDX_ITEM_MIX_DATE (NOTIFICATION_DATE),
  KEY IDX_ITEM_MIX_MITEM (MIXTURE_ITEM_SEQ)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 병용금기(복합 PK)';

DROP TABLE IF EXISTS ITEM_ELDERLY_CAUTION;
CREATE TABLE ITEM_ELDERLY_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 노인주의',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_ELDERLY_INGR (INGR_CODE),
  KEY IDX_ITEM_ELDERLY_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 노인주의';

DROP TABLE IF EXISTS ITEM_DUR_INFO;
CREATE TABLE ITEM_DUR_INFO (
  ITEM_SEQ           VARCHAR(20)  NOT NULL COMMENT '품목 기준코드(원문 키)',
  ITEM_NAME          VARCHAR(500) NULL     COMMENT '품목명',
  ENTP_NAME          VARCHAR(500) NULL     COMMENT '제조/수입사명',
  ITEM_PERMIT_DATE   VARCHAR(100)  NULL     COMMENT '품목 허가일(원문)',
  ETC_OTC_CODE       VARCHAR(20)  NULL     COMMENT '전문/일반 코드 또는 명',
  CLASS_NO           VARCHAR(60)  NULL     COMMENT '분류번호(예: [222]진해거담제)',
  CHART              TEXT         NULL     COMMENT '성상',
  BAR_CODE           VARCHAR(50)  NULL     COMMENT '바코드',
  MATERIAL_NAME      TEXT         NULL     COMMENT '원료성분/규격',
  EE_DOC_ID          VARCHAR(500) NULL     COMMENT '효능효과 문서 링크',
  UD_DOC_ID          VARCHAR(500) NULL     COMMENT '용법용량 문서 링크',
  NB_DOC_ID          VARCHAR(500) NULL     COMMENT '주의사항 문서 링크',
  INSERT_FILE        VARCHAR(500) NULL     COMMENT '첨부문서 링크',
  STORAGE_METHOD     TEXT         NULL     COMMENT '보관방법',
  VALID_TERM         VARCHAR(100) NULL     COMMENT '유효기간',
  REEXAM_TARGET      VARCHAR(100) NULL     COMMENT '재심사 대상',
  REEXAM_DATE        VARCHAR(100)  NULL     COMMENT '재심사 기간/일자(원문)',
  PACK_UNIT          VARCHAR(2000) NULL     COMMENT '포장단위',
  EDI_CODE           VARCHAR(50)  NULL     COMMENT 'EDI 코드',
  CANCEL_DATE        VARCHAR(20)  NULL     COMMENT '허가취소일(원문)',
  CANCEL_NAME        VARCHAR(20)  NULL     COMMENT '허가상태(정상/취소 등)',
  TYPE_CODE          VARCHAR(200)   NULL     COMMENT 'DUR 유형 코드',
  TYPE_NAME          VARCHAR(20)  NULL     COMMENT 'DUR 유형명',
  CHANGE_DATE        VARCHAR(100)  NULL     COMMENT '변경일(원문)',
  BIZRNO             VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),                         -- 메타는 ITEM_SEQ가 자연키
  KEY IDX_ITEM_DUR_CHANGE (CHANGE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목 메타정보(ITEM_SEQ PK)';

DROP TABLE IF EXISTS ITEM_AGE_CONTRAINDICATION;
CREATE TABLE ITEM_AGE_CONTRAINDICATION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 특정연령대금기',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '금기/주의 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_AGE_INGR (INGR_CODE),
  KEY IDX_ITEM_AGE_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 특정연령대금기';

DROP TABLE IF EXISTS ITEM_DOSE_CAUTION;
CREATE TABLE ITEM_DOSE_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 용량주의',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용(최대 허용량 등)',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_DOSE_INGR (INGR_CODE),
  KEY IDX_ITEM_DOSE_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 용량주의';

DROP TABLE IF EXISTS ITEM_DURATION_CAUTION;
CREATE TABLE ITEM_DURATION_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 투여기간주의',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용(최대 투여기간 등)',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_DUR_INGR (INGR_CODE),
  KEY IDX_ITEM_DUR_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 투여기간주의';

DROP TABLE IF EXISTS ITEM_THERAPEUTIC_DUPLICATION;
CREATE TABLE ITEM_THERAPEUTIC_DUPLICATION (
  DUR_SEQ              BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  EFFECT_NAME          VARCHAR(500) NULL     COMMENT '효능군명',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 효능군중복',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  FORM_CODE_NAME       VARCHAR(500) NULL     COMMENT '제형 코드명',
  MIX                  VARCHAR(20)  NULL     COMMENT '혼합 유형',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  CHART                TEXT         NULL     COMMENT '성상',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  FORM_CODE            VARCHAR(20)  NULL     COMMENT '제형 코드',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ETC_OTC_CODE         VARCHAR(20)  NULL     COMMENT '전문/일반 코드',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '금기/주의 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  BIZRNO               VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  SERS_NAME            VARCHAR(500) NULL     COMMENT '상세 계열/군 명칭',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_ITEM_TD_ITEM (ITEM_SEQ),
  KEY IDX_ITEM_TD_INGR (INGR_CODE),
  KEY IDX_ITEM_TD_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 효능군중복';

DROP TABLE IF EXISTS ITEM_SUSTAINED_RELEASE_SPLIT_CAUTION;
CREATE TABLE ITEM_SUSTAINED_RELEASE_SPLIT_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 분할주의',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(100)  NULL     COMMENT '품목 허가일(원문, 예: 1971May6th)',
  FORM_CODE_NAME       VARCHAR(500) NULL     COMMENT '제형 코드명(예: 장용성필름코팅정)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MIX                  VARCHAR(20)  NULL     COMMENT '혼합 유형: 복합/단일',
  MAIN_INGR            VARCHAR(700) NULL     COMMENT '주성분 원문(복합 가능)',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용(예: 분할불가)',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  BIZRNO               VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_SR_CHANGE (CHANGE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 서방정 분할주의';

DROP TABLE IF EXISTS ITEM_PREGNANCY_CONTRAINDICATION;
CREATE TABLE ITEM_PREGNANCY_CONTRAINDICATION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 임부금기',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             VARCHAR(500) NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '금기 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_PREG_INGR (INGR_CODE),
  KEY IDX_ITEM_PREG_DATE (NOTIFICATION_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='DUR 품목: 임부금기';



/* =========================================================
   5) 질병/증상 마스터 테이블
   - 크롤링 데이터 : 아산병원 질환백과
========================================================= */

-- 1. 질병 마스터 테이블
CREATE TABLE IF NOT EXISTS disease_master (
    disease_id           BIGINT AUTO_INCREMENT PRIMARY KEY,
    disease_name_kor     VARCHAR(200) NOT NULL,         -- 질병명 (한글)
    disease_name_eng     VARCHAR(200),                  -- 질병명 (영문, 없을 수 있음)
    symptoms             TEXT,                          -- 증상 리스트 (쉼표로 구분된 문자열)
    description          TEXT,                          -- 질병 설명 (본문)
    source_url           TEXT,                          -- 원본 URL
    created_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);



/* =========================================================
   6) 러닝 임베딩 캐시 데이터 ?
========================================================= */
CREATE TABLE IF NOT EXISTS disease_embedding_item (
  ITEM_SEQ      VARCHAR(20)   NOT NULL PRIMARY KEY,
  TEXT_HASH     CHAR(64)      NOT NULL, -- 텍스트+모델 해시
  TEXT_SOURCE   LONGTEXT      NOT NULL, -- 임베딩에 사용한 원문
  DIM           INT           NOT NULL, -- 임베딩 차원
  EMBEDDING     JSON          NOT NULL, -- float 배열(JSON)
  UPDATED_AT    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);






/* ======================================================
뻘짓한거 수정하고 있는 버전 추가 테이블
=========================================================*/
/* ===========================================
  SOURCE_PAGE: 원문 페이지(아산/위키) 보관
=========================================== */
CREATE TABLE IF NOT EXISTS SOURCE_PAGE (
  SOURCE_PAGE_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=SOURCE_PAGE_ID | 설명: 원문 페이지 고유 ID(AUTO_INCREMENT)',
  SOURCE ENUM('AMC','WIKIPEDIA') NOT NULL COMMENT '컬럼명=SOURCE | 설명: 수집 원천(AMC=아산병원, WIKIPEDIA=위키백과)',
  LANG VARCHAR(8) NOT NULL DEFAULT 'ko' COMMENT '컬럼명=LANG | 설명: 페이지 언어(ko 등)',
  PAGE_ID BIGINT NULL COMMENT '컬럼명=PAGE_ID | 설명: 위키 pageid (AMC는 NULL)',
  REV_ID BIGINT NULL COMMENT '컬럼명=REV_ID | 설명: 위키 revid(버전 식별자)',
  TITLE VARCHAR(500) NOT NULL COMMENT '컬럼명=TITLE | 설명: 페이지 제목',
  URL TEXT NOT NULL COMMENT '컬럼명=URL | 설명: 원문 페이지 URL',
  CATEGORY_PATH TEXT NULL COMMENT '컬럼명=CATEGORY_PATH | 설명: 분류 경로(JSON 또는 문자열 경로)',
  RAW_WIKITEXT LONGTEXT NULL COMMENT '컬럼명=RAW_WIKITEXT | 설명: 위키텍스트 원문(위키 전용)',
  RAW_HTML LONGTEXT NULL COMMENT '컬럼명=RAW_HTML | 설명: 렌더링된 HTML 원문(AMC/위키 공통)',
  HASH_SHA1 CHAR(40) NOT NULL COMMENT '컬럼명=HASH_SHA1 | 설명: 본문 해시(중복/변경 감지)',
  CRAWLED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '컬럼명=CRAWLED_AT | 설명: 수집 시각',
  -- UNIQUE KEY UK_SRC (SOURCE, (IFNULL(PAGE_ID, 0)), (IFNULL(REV_ID, 0)), HASH_SHA1),
  KEY IDX_SRC_TITLE (TITLE(200))
) COMMENT='원문 페이지 보관(아산/위키, 버전/중복 관리)';

ALTER TABLE SOURCE_PAGE
  ADD COLUMN PAGE_ID_NZ BIGINT AS (IFNULL(PAGE_ID, 0)) PERSISTENT,
  ADD COLUMN REV_ID_NZ  BIGINT AS (IFNULL(REV_ID, 0))  PERSISTENT,
  ADD UNIQUE KEY UK_SRC (SOURCE, PAGE_ID_NZ, REV_ID_NZ, HASH_SHA1);


/* ===========================================
  SOURCE_SECTION: 섹션별 정제 텍스트
=========================================== */
CREATE TABLE IF NOT EXISTS SOURCE_SECTION (
  SECTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=SECTION_ID | 설명: 섹션 고유 ID(AUTO_INCREMENT)',
  SOURCE_PAGE_ID BIGINT NOT NULL COMMENT '컬럼명=SOURCE_PAGE_ID | 설명: 상위 원문 페이지 ID(FK)',
  SECTION_NAME VARCHAR(100) NOT NULL COMMENT '컬럼명=SECTION_NAME | 설명: 섹션명(개요/증상/치료/원인/예방 등)',
  ORDER_NO INT NOT NULL COMMENT '컬럼명=ORDER_NO | 설명: 페이지 내 섹션 순서',
  TEXT_CLEAN LONGTEXT NOT NULL COMMENT '컬럼명=TEXT_CLEAN | 설명: 태그 제거/문장 분할 등 정제 텍스트',
  TEXT_JSON LONGTEXT NULL COMMENT '컬럼명=TEXT_JSON | 설명: 표/리스트 등 구조화 JSON',
  FOREIGN KEY (SOURCE_PAGE_ID) REFERENCES SOURCE_PAGE(SOURCE_PAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  KEY IDX_SEC_NAME (SECTION_NAME)
) COMMENT='페이지 섹션 정규화(클린 텍스트/JSON)';


/* ===========================================
  SYMPTOM_LEXICON: 증상 표제어(정규화 대상)
=========================================== */
CREATE TABLE IF NOT EXISTS SYMPTOM_LEXICON (
  SYMPTOM_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=SYMPTOM_ID | 설명: 증상 표제어 ID(AUTO_INCREMENT)',
  CANONICAL_NAME VARCHAR(120) NOT NULL COMMENT '컬럼명=CANONICAL_NAME | 설명: 표준 증상명(예: 오한, 호흡곤란)',
  ICD10_CODE VARCHAR(10) NULL COMMENT '컬럼명=ICD10_CODE | 설명: (선택) 관련 ICD-10 코드',
  UMLS_CUI VARCHAR(20) NULL COMMENT '컬럼명=UMLS_CUI | 설명: (선택) UMLS CUI',
  DESCRIPTION TEXT NULL COMMENT '컬럼명=DESCRIPTION | 설명: 증상 설명(간단 정의)',
  UNIQUE KEY UK_SYMP_NAME (CANONICAL_NAME)
) COMMENT='증상 표준 사전(표제어)';



/* ===========================================
  SYMPTOM_ALIAS: 증상 별칭(구어/오타 포함)
=========================================== */
CREATE TABLE IF NOT EXISTS SYMPTOM_ALIAS (
  ALIAS_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=ALIAS_ID | 설명: 별칭 레코드 ID(AUTO_INCREMENT)',
  SYMPTOM_ID BIGINT NOT NULL COMMENT '컬럼명=SYMPTOM_ID | 설명: 연결된 표제어 ID(FK)',
  ALIAS VARCHAR(200) NOT NULL COMMENT '컬럼명=ALIAS | 설명: 구어체/오타/표현(예: 몸이 떨리고 춥다)',
  SOURCE ENUM('AMC','WIKIPEDIA','MANUAL','KBMC') NOT NULL COMMENT '컬럼명=SOURCE | 설명: 별칭 출처',
  CONFIDENCE DECIMAL(4,3) DEFAULT 0.800 COMMENT '컬럼명=CONFIDENCE | 설명: 매핑 신뢰도(0~1)',
  FOREIGN KEY (SYMPTOM_ID) REFERENCES SYMPTOM_LEXICON(SYMPTOM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  UNIQUE KEY UK_ALIAS (ALIAS),
  KEY IDX_SYMPTOM_ID (SYMPTOM_ID)
) COMMENT='증상 표제어-별칭 매핑(정규화 사전)';



/* ===========================================
  DISEASE_SYMPTOM_MAP: 질병-증상 연결(가중치)
  - disease_master(disease_id) 존재 가정
=========================================== */
CREATE TABLE IF NOT EXISTS DISEASE_SYMPTOM_MAP (
  DISEASE_ID BIGINT NOT NULL COMMENT '컬럼명=DISEASE_ID | 설명: 질병 ID(FK, disease_master)',
  SYMPTOM_ID BIGINT NOT NULL COMMENT '컬럼명=SYMPTOM_ID | 설명: 증상 표제어 ID(FK)',
  WEIGHT_SCORE DECIMAL(5,2) DEFAULT 1.00 COMMENT '컬럼명=WEIGHT_SCORE | 설명: 연관 강도/특이도 기반 가중치',
  EVIDENCE_SOURCE ENUM('AMC','WIKIPEDIA','DUR','NER') NOT NULL COMMENT '컬럼명=EVIDENCE_SOURCE | 설명: 근거 출처',
  EVIDENCE_SPAN TEXT NULL COMMENT '컬럼명=EVIDENCE_SPAN | 설명: 근거 문장/섹션 발췌',
  PRIMARY KEY (DISEASE_ID, SYMPTOM_ID), 
  FOREIGN KEY (DISEASE_ID) REFERENCES disease_master(disease_id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (SYMPTOM_ID) REFERENCES SYMPTOM_LEXICON(SYMPTOM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  KEY IDX_MAP_SYMPTOM (SYMPTOM_ID),
  KEY IDX_MAP_DISEASE (DISEASE_ID)
) COMMENT='질병-증상 매핑(증상 기반 후보 검색/재랭킹에 사용)';


/* ===========================================
  NER_CORPUS_REGISTRY: 코퍼스/모델 아티팩트 메타
=========================================== */
CREATE TABLE IF NOT EXISTS NER_CORPUS_REGISTRY (
  CORPUS_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=CORPUS_ID | 설명: 코퍼스 메타 ID(AUTO_INCREMENT)',
  NAME VARCHAR(200) NOT NULL COMMENT '컬럼명=NAME | 설명: 코퍼스 이름(예: KBMC)',
  URL TEXT NOT NULL COMMENT '컬럼명=URL | 설명: 출처/다운로드 경로',
  LICENSE VARCHAR(100) NOT NULL COMMENT '컬럼명=LICENSE | 설명: 라이선스(예: Apache-2.0)',
  ENTITY_TYPES VARCHAR(200) NOT NULL COMMENT '컬럼명=ENTITY_TYPES | 설명: 엔티티 타입 목록(쉼표 구분)',
  NUM_SENTENCES INT NULL COMMENT '컬럼명=NUM_SENTENCES | 설명: 문장 수(가능 시)',
  LOCAL_PATH VARCHAR(500) NULL COMMENT '컬럼명=LOCAL_PATH | 설명: 로컬 저장 경로(압축/가공본)',
  IMPORTED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '컬럼명=IMPORTED_AT | 설명: 반입 시각',
  UNIQUE KEY UK_CORPUS_NAME (NAME)
) COMMENT='NER 코퍼스/모델 메타(추적/재현성)';


/* ===========================================
  DISEASE_EMBEDDING_ITEM: 임베딩 캐시(요청 반영)
  - 텍스트+모델 해시로 멱등 캐싱
=========================================== */
CREATE TABLE IF NOT EXISTS DISEASE_EMBEDDING_ITEM (
  ITEM_SEQ VARCHAR(64) NOT NULL PRIMARY KEY COMMENT '컬럼명=ITEM_SEQ | 설명: 임베딩 항목 ID(예: 해시 또는 UUID)',
  TEXT_HASH CHAR(64) NOT NULL COMMENT '컬럼명=TEXT_HASH | 설명: (텍스트+모델명) SHA-256 해시',
  TEXT_SOURCE LONGTEXT NOT NULL COMMENT '컬럼명=TEXT_SOURCE | 설명: 임베딩 대상 원문(질병 설명/증상 문장 등)',
  DIM INT NOT NULL COMMENT '컬럼명=DIM | 설명: 임베딩 차원',
  EMBEDDING JSON NOT NULL COMMENT '컬럼명=EMBEDDING | 설명: float 배열(JSON)',
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '컬럼명=UPDATED_AT | 설명: 업데이트 시각',
  KEY IDX_TEXT_HASH (TEXT_HASH)
) COMMENT='임베딩 캐시(증상/질병 검색·재랭킹 가속)';



/* ===========================================
  ETL_JOB_RUNS: ETL 실행 이력/메트릭
=========================================== */
CREATE TABLE IF NOT EXISTS ETL_JOB_RUNS (
  RUN_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=RUN_ID | 설명: 실행 ID(AUTO_INCREMENT)',
  JOB_NAME VARCHAR(120) NOT NULL COMMENT '컬럼명=JOB_NAME | 설명: 작업명(CRAWL_WIKI/CRAWL_AMC/DUR_SYNC 등)',
  SOURCE VARCHAR(50) NOT NULL COMMENT '컬럼명=SOURCE | 설명: 데이터 원천(WIKIPEDIA/AMC/DUR)',
  STARTED_AT DATETIME NOT NULL COMMENT '컬럼명=STARTED_AT | 설명: 시작 시각',
  ENDED_AT DATETIME NULL COMMENT '컬럼명=ENDED_AT | 설명: 종료 시각',
  STATUS ENUM('SUCCESS','FAILED','PARTIAL') NOT NULL COMMENT '컬럼명=STATUS | 설명: 실행 결과 상태',
  ROWS_IN INT NULL COMMENT '컬럼명=ROWS_IN | 설명: 입력(수집) 행 수',
  ROWS_UPSERTED INT NULL COMMENT '컬럼명=ROWS_UPSERTED | 설명: 업서트 행 수',
  ROWS_SKIPPED INT NULL COMMENT '컬럼명=ROWS_SKIPPED | 설명: 스킵 행 수',
  LOG_SUMMARY TEXT NULL COMMENT '컬럼명=LOG_SUMMARY | 설명: 요약 로그/오류 메시지',
  KEY IDX_JOB_TIME (JOB_NAME, STARTED_AT)
) COMMENT='ETL 실행 로그/메트릭(운영/리트라이 근거)';


/* ===========================================
  CRAWL_QUEUE: 크롤링 대기열(멱등/우선순위)
=========================================== */
CREATE TABLE IF NOT EXISTS CRAWL_QUEUE (
  QID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=QID | 설명: 큐 항목 ID(AUTO_INCREMENT)',
  SOURCE ENUM('AMC','WIKIPEDIA') NOT NULL COMMENT '컬럼명=SOURCE | 설명: 원천(AMC/위키)',
  LANG VARCHAR(8) NOT NULL DEFAULT 'ko' COMMENT '컬럼명=LANG | 설명: 대상 언어',
  URL_OR_TITLE VARCHAR(800) NOT NULL COMMENT '컬럼명=URL_OR_TITLE | 설명: AMC=URL, 위키=TITLE',
  PRIORITY TINYINT NOT NULL DEFAULT 5 COMMENT '컬럼명=PRIORITY | 설명: 우선순위(낮을수록 높음)',
  ENQ_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '컬럼명=ENQ_AT | 설명: 대기열 등록 시각',
  DEQ_AT DATETIME NULL COMMENT '컬럼명=DEQ_AT | 설명: 디큐/처리 시각',
  STATUS ENUM('PENDING','FETCHED','ERROR','SKIPPED') NOT NULL DEFAULT 'PENDING' COMMENT '컬럼명=STATUS | 설명: 상태(PENDING/FETCHED/ERROR/SKIPPED)',
  ERROR_MSG VARCHAR(500) NULL COMMENT '컬럼명=ERROR_MSG | 설명: 오류 메시지(있을 경우)',
  UNIQUE KEY UK_ITEM (SOURCE, URL_OR_TITLE),
  KEY IDX_Q_STATUS (STATUS, PRIORITY, ENQ_AT)
) COMMENT='크롤링 대기열(중복 방지/리트라이 관리)';

ALTER TABLE CRAWL_QUEUE ADD COLUMN UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER DEQ_AT;

/* ===========================================
  DUR_RAW_PRODUCT: DUR 품목 원문 보존
=========================================== */
CREATE TABLE IF NOT EXISTS DUR_RAW_PRODUCT (
  RAW_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=RAW_ID | 설명: 원문 레코드 ID(AUTO_INCREMENT)',
  FETCHED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '컬럼명=FETCHED_AT | 설명: 수집 시각',
  SOURCE_JSON LONGTEXT NOT NULL COMMENT '컬럼명=SOURCE_JSON | 설명: 원문 JSON(품목)',
  HASH_SHA1 CHAR(40) NOT NULL COMMENT '컬럼명=HASH_SHA1 | 설명: 원문 해시(중복 방지)',
  UNIQUE KEY UK_DUR_RAW (HASH_SHA1)
) COMMENT='DUR 원문(품목) 스냅샷 보존';

/* ===========================================
  DUR_RAW_SUBSTANCE: DUR 성분 원문 보존
=========================================== */
CREATE TABLE IF NOT EXISTS DUR_RAW_SUBSTANCE (
  RAW_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=RAW_ID | 설명: 원문 레코드 ID(AUTO_INCREMENT)',
  FETCHED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '컬럼명=FETCHED_AT | 설명: 수집 시각',
  SOURCE_JSON LONGTEXT NOT NULL COMMENT '컬럼명=SOURCE_JSON | 설명: 원문 JSON(성분)',
  HASH_SHA1 CHAR(40) NOT NULL COMMENT '컬럼명=HASH_SHA1 | 설명: 원문 해시(중복 방지)',
  UNIQUE KEY UK_DUR_RAW (HASH_SHA1)
) COMMENT='DUR 원문(성분) 스냅샷 보존';



/* ===========================================
  SOURCE_PAGE_DISEASE: 원문 페이지 ↔ 질병 연결(선택사항)
=========================================== */
CREATE TABLE IF NOT EXISTS SOURCE_PAGE_DISEASE (
  LINK_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '컬럼명=LINK_ID | 설명: 연결 레코드 ID(AUTO_INCREMENT)',
  SOURCE_PAGE_ID BIGINT NOT NULL COMMENT '컬럼명=SOURCE_PAGE_ID | 설명: 원문 페이지 ID(FK)',
  DISEASE_ID BIGINT NOT NULL COMMENT '컬럼명=DISEASE_ID | 설명: 질병 ID(FK, disease_master)',
  MATCH_CONF DECIMAL(4,3) NOT NULL DEFAULT 1.000 COMMENT '컬럼명=MATCH_CONF | 설명: 매칭 신뢰도(자동 매칭 시)',
  UNIQUE KEY UK_PAGE_DZ (SOURCE_PAGE_ID, DISEASE_ID),
  FOREIGN KEY (SOURCE_PAGE_ID) REFERENCES SOURCE_PAGE(SOURCE_PAGE_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (DISEASE_ID) REFERENCES disease_master(disease_id) ON UPDATE CASCADE ON DELETE CASCADE
) COMMENT='원문 페이지와 질병 마스터의 연결(명시적 링크)';




/* ----------------------------------------------
AMC_INDEX_SEED: 아산 질환백과 인덱스 시딩 잡 메타
---------------------------------------------- */
CREATE TABLE IF NOT EXISTS AMC_INDEX_SEED (
	SEED_ID BIGINT AUTO_INCREMENT PRIMARY KEY
	COMMENT '컬럼명=SEED_ID | 설명: 시딩 잡 ID(AUTO_INCREMENT)',
	ROOT_URL VARCHAR(800) NOT NULL
	COMMENT '컬럼명=ROOT_URL | 설명: 시작 인덱스 URL(예: 목록/사전/검색 페이지)',
	PAGINATION_MODE ENUM('QUERY_PARAM','LINK_NEXT','CSS_SELECTOR') NOT NULL DEFAULT 'QUERY_PARAM'
	COMMENT '컬럼명=PAGINATION_MODE | 설명: 페이지네이션 방식',
	QUERY_PARAM_NAME VARCHAR(64) NOT NULL DEFAULT 'page'
	COMMENT '컬럼명=QUERY_PARAM_NAME | 설명: QUERY_PARAM 모드일 때 페이지 파라미터명',
	START_PAGE INT NOT NULL DEFAULT 1
	COMMENT '컬럼명=START_PAGE | 설명: 시작 페이지 번호',
	CSS_NEXT_SELECTOR VARCHAR(255) NULL
	COMMENT '컬럼명=CSS_NEXT_SELECTOR | 설명: CSS_SELECTOR 모드일 때 next 링크 CSS',
	RPS DECIMAL(6,3) NOT NULL DEFAULT 0.300
	COMMENT '컬럼명=RPS | 설명: 초당 요청 수(레이트리밋)',
	STATUS ENUM('PENDING','RUNNING','PAUSED','DONE','ERROR') NOT NULL DEFAULT 'PENDING'
	COMMENT '컬럼명=STATUS | 설명: 진행 상태',
	PAGES_SCANNED INT NOT NULL DEFAULT 0
	COMMENT '컬럼명=PAGES_SCANNED | 설명: 스캔한 인덱스 페이지 수',
	DETAILS_ENQUEUED INT NOT NULL DEFAULT 0
	COMMENT '컬럼명=DETAILS_ENQUEUED | 설명: 큐에 넣은 상세 페이지 수',
	LAST_MESSAGE VARCHAR(500) NULL
	COMMENT '컬럼명=LAST_MESSAGE | 설명: 최근 상태/오류 메시지',
	CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	COMMENT '컬럼명=CREATED_AT | 설명: 생성 시각',
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	COMMENT '컬럼명=UPDATED_AT | 설명: 최근 갱신 시각',
	KEY IDX_AMC_SEED_STATUS (STATUS, UPDATED_AT)
) COMMENT='아산 인덱스 시딩 잡 메타';


/* ----------------------------------------------
AMC_INDEX_TODO: 진행 커서 저장(현재 URL/페이지 번호/다음 링크)
---------------------------------------------- */
CREATE TABLE IF NOT EXISTS AMC_INDEX_TODO (
	TODO_ID BIGINT AUTO_INCREMENT PRIMARY KEY
	COMMENT '컬럼명=TODO_ID | 설명: TODO 항목 ID(AUTO_INCREMENT)',
	SEED_ID BIGINT NOT NULL
	COMMENT '컬럼명=SEED_ID | 설명: 상위 시딩 잡 ID(FK)',
	CURRENT_URL VARCHAR(800) NOT NULL
	COMMENT '컬럼명=CURRENT_URL | 설명: 현재 처리 중인 인덱스 페이지 URL',
	PAGE_NO INT NOT NULL
	COMMENT '컬럼명=PAGE_NO | 설명: 현재 페이지 번호(QUERY_PARAM 모드 기준)',
	NEXT_HINT VARCHAR(800) NULL
	COMMENT '컬럼명=NEXT_HINT | 설명: 발견된 다음 페이지 링크 또는 힌트',
	STATUS ENUM('PENDING','IN_PROGRESS','DONE','ERROR') NOT NULL DEFAULT 'PENDING'
	COMMENT '컬럼명=STATUS | 설명: 처리 상태',
	LAST_ERROR VARCHAR(500) NULL
	COMMENT '컬럼명=LAST_ERROR | 설명: 최근 오류 메시지',
	UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	COMMENT '컬럼명=UPDATED_AT | 설명: 최근 갱신 시각',
	UNIQUE KEY UK_AMC_TODO (SEED_ID, CURRENT_URL),
	FOREIGN KEY (SEED_ID) REFERENCES AMC_INDEX_SEED(SEED_ID)
	ON UPDATE CASCADE ON DELETE CASCADE,
	KEY IDX_AMC_TODO_STATUS (STATUS, UPDATED_AT)
) COMMENT='아산 인덱스 시딩 진행 커서(중단/재개)';

ALTER TABLE CRAWL_QUEUE
  modify COLUMN UPDATED_AT DATETIME NOT NULL
    DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    AFTER DEQ_AT;


/* ----------------------------------------------
  WIKI_CATEGORY_SEED: 위키 카테고리 시딩 잡 메타
---------------------------------------------- */
CREATE TABLE IF NOT EXISTS WIKI_CATEGORY_SEED (
  SEED_ID            BIGINT AUTO_INCREMENT PRIMARY KEY
    COMMENT '컬럼명=SEED_ID | 설명: 시딩 잡 ID(AUTO_INCREMENT)',
  ROOT_CATEGORY      VARCHAR(255) NOT NULL
    COMMENT '컬럼명=ROOT_CATEGORY | 설명: 루트 카테고리(예: 분류:질병)',
  DEPTH_LIMIT        INT NOT NULL DEFAULT 1
    COMMENT '컬럼명=DEPTH_LIMIT | 설명: 하위 분류 재귀 최대 깊이',
  INCLUDE_SUBCATS    TINYINT(1) NOT NULL DEFAULT 1
    COMMENT '컬럼명=INCLUDE_SUBCATS | 설명: 하위 분류 포함 여부(1/0)',
  RPS                DECIMAL(6,3) NOT NULL DEFAULT 0.500
    COMMENT '컬럼명=RPS | 설명: 초당 요청 수(레이트리밋)',
  STATUS             ENUM('PENDING','RUNNING','PAUSED','DONE','ERROR') NOT NULL DEFAULT 'PENDING'
    COMMENT '컬럼명=STATUS | 설명: 진행 상태',
  API_CALLS_TOTAL    INT NOT NULL DEFAULT 0
    COMMENT '컬럼명=API_CALLS_TOTAL | 설명: 누적 API 호출 수',
  PAGES_ENQUEUED     INT NOT NULL DEFAULT 0
    COMMENT '컬럼명=PAGES_ENQUEUED | 설명: 큐에 넣은 문서(페이지) 수',
  SUBCATS_DISCOVERED INT NOT NULL DEFAULT 0
    COMMENT '컬럼명=SUBCATS_DISCOVERED | 설명: 발견한 하위 분류 수',
  LAST_MESSAGE       VARCHAR(500) NULL
    COMMENT '컬럼명=LAST_MESSAGE | 설명: 최근 상태/오류 메시지',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    COMMENT '컬럼명=CREATED_AT | 설명: 생성 시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    COMMENT '컬럼명=UPDATED_AT | 설명: 최근 갱신 시각',
  KEY IDX_SEED_STATUS (STATUS, UPDATED_AT)
) COMMENT='위키 카테고리 시딩 잡 메타';

/* ----------------------------------------------
  WIKI_CATEGORY_TODO: 카테고리 단위 진행 커서(cmcontinue) 저장
---------------------------------------------- */
CREATE TABLE IF NOT EXISTS WIKI_CATEGORY_TODO (
  TODO_ID       BIGINT AUTO_INCREMENT PRIMARY KEY
    COMMENT '컬럼명=TODO_ID | 설명: TODO 항목 ID(AUTO_INCREMENT)',
  SEED_ID       BIGINT NOT NULL
    COMMENT '컬럼명=SEED_ID | 설명: 상위 시딩 잡 ID(FK)',
  CATEGORY      VARCHAR(255) NOT NULL
    COMMENT '컬럼명=CATEGORY | 설명: 현재 처리할 카테고리(예: 분류:감염병)',
  DEPTH         INT NOT NULL
    COMMENT '컬럼명=DEPTH | 설명: 루트 대비 현재 깊이',
  CMCONTINUE    VARCHAR(255) NULL
    COMMENT '컬럼명=CMCONTINUE | 설명: 위키 categorymembers 다음 페이지 커서',
  STATUS        ENUM('PENDING','IN_PROGRESS','DONE','ERROR') NOT NULL DEFAULT 'PENDING'
    COMMENT '컬럼명=STATUS | 설명: 처리 상태',
  LAST_ERROR    VARCHAR(500) NULL
    COMMENT '컬럼명=LAST_ERROR | 설명: 최근 오류 메시지',
  UPDATED_AT    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    COMMENT '컬럼명=UPDATED_AT | 설명: 최근 갱신 시각',
  UNIQUE KEY UK_SEED_CAT_DEPTH (SEED_ID, CATEGORY, DEPTH),
  FOREIGN KEY (SEED_ID) REFERENCES WIKI_CATEGORY_SEED(SEED_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
  KEY IDX_TODO_STATUS (STATUS, UPDATED_AT)
) COMMENT='시딩 진행 커서(cmcontinue) 저장(중단/재개)';


ALTER TABLE WIKI_CATEGORY_TODO
  ADD COLUMN IF NOT EXISTS PAGE_CONTINUE VARCHAR(255) NULL COMMENT 'categorymembers 이어받기 토큰',
  ADD COLUMN IF NOT EXISTS LAST_ERROR    VARCHAR(500) NULL COMMENT '마지막 오류 메시지';

-- 2) 상태값 확장 (ENUM이면 IN_PROGRESS/ERROR 추가, VARCHAR라면 건너뛰어도 OK)
-- ENUM이 아닐 수도 있으니, 실패하면 이 구문은 건너뛰세요.
ALTER TABLE WIKI_CATEGORY_TODO
  MODIFY STATUS ENUM('PENDING','IN_PROGRESS','DONE','ERROR') NOT NULL DEFAULT 'PENDING';

-- 3) 조회·스케줄 편의를 위한 인덱스(선택)
CREATE INDEX IF NOT EXISTS IX_WIKI_TODO_STATUS ON WIKI_CATEGORY_TODO (STATUS, UPDATED_AT);
CREATE INDEX IF NOT EXISTS IX_WIKI_TODO_SEED   ON WIKI_CATEGORY_TODO (SEED_ID, STATUS);