/* ========================================================================
  YAME: 디지털 예진 운영/레퍼런스 스키마 (MySQL/InnoDB)
  - 규칙: 모든 객체 UPPER_SNAKE_CASE, 키워드 대문자
  - PK 기본 전략: 밀리초 타임스탬프(로그성 테이블) 또는 AUTO_INCREMENT
  - 좌표 규칙: X=경도(LON), Y=위도(LAT), POINT(x,y)
========================================================================= */


/* =========================================================
  1) 운영 핵심 (개인식별 없음)
========================================================= */

-- ----------------------------------------------------------------------
-- SYMPTOM_LOGS: 증상 로그 수집 (익명)
-- ----------------------------------------------------------------------
DROP TABLE IF EXISTS SYMPTOM_LOGS;
CREATE TABLE IF NOT EXISTS SYMPTOM_LOGS (
  LOG_ID            BIGINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '증상 이벤트 고유 ID(자동증가)',
  SYMPTOM_TEXT      TEXT NOT NULL COMMENT '사용자 입력 증상 원문(자유기술 포함)',
  SUB_SYMPTOMS      JSON NULL COMMENT '보조 증상 배열(JSON, 예: ["기침","콧물"])',
  PREDICTED_DISEASE VARCHAR(120) COMMENT 'ML이 추정한 질병 라벨(정규화 키 또는 한글명)',
  RECOMMENDATION    ENUM('PHARMACY','HOSPITAL') NOT NULL COMMENT '권유 분기: 약국(PHARMACY) 또는 병원(HOSPITAL)',
  DRUG_SUGGESTED    VARCHAR(120) COMMENT '추천 OTC 약품명(있을 때만 저장)',
  ITEM_SEQ               VARCHAR(20)  NOT NULL COMMENT '품목 기준코드(DUR)',
  ITEM_NAME              VARCHAR(500) NULL     COMMENT '품목명(DUR)',
  DUR_FLAGS         JSON NULL COMMENT 'DUR 관련 위반/주의 플래그 목록(JSON 배열)',
  REGION_LABEL      VARCHAR(120) COMMENT '주소 라벨(행정구/동 등, 통계용)',
  LONGITUDE         VARCHAR(20) COMMENT '경도',
  LATITUDE          VARCHAR(20) COMMENT '위도',
  GPS_ACCURACY_M    INT NULL COMMENT 'GPS 정확도(미터 단위)',
  CREATED_AT        DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '수집 시각(KST 기준)',
  INDEX IDX_LOGS_CREATED (CREATED_AT) COMMENT '시간순 조회용 색인',
  INDEX IDX_LOGS_RECO (RECOMMENDATION, CREATED_AT) COMMENT '권유타입+시간 복합색인',
  INDEX IDX_LOGS_DISEASE (PREDICTED_DISEASE(64), CREATED_AT) COMMENT '질병별 집계용 색인',
  INDEX IDX_LOGS_REGION (REGION_LABEL(64), CREATED_AT) COMMENT '지역별 통계용 색인'
)  COMMENT='증상 로그(익명 수집, 통계/ML 학습 원천)';




/* =========================================================
  2) 기관/시설 마스터
========================================================= */

-- ----------------------------------------------------------------------
-- HIRA_HOSPITAL_INFO: 심평원 병원 정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS HIRA_HOSPITAL_INFO (
  ID               BIGINT UNSIGNED NOT NULL PRIMARY KEY
                     DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  YKIHO            VARCHAR(500)  NOT NULL COMMENT '요양기관 기호(암호화)',
  YADM_NM          VARCHAR(500) NULL COMMENT '기관명',
  TELNO            VARCHAR(30)  NULL COMMENT '전화번호',
  HOSP_URL         VARCHAR(500) NULL COMMENT '홈페이지 URL',
  CL_CD            VARCHAR(10)  NULL COMMENT '종별 코드',
  CL_CD_NM         VARCHAR(80)  NULL COMMENT '종별 명칭',
  SIDO_CD          VARCHAR(10)  NULL COMMENT '시도 코드',
  SIDO_CD_NM       VARCHAR(50)  NULL COMMENT '시도 명칭',
  SGGU_CD          VARCHAR(10)  NULL COMMENT '시군구 코드',
  SGGU_CD_NM       VARCHAR(50)  NULL COMMENT '시군구 명칭',
  ADDR             VARCHAR(500) NULL COMMENT '주소',
  EMDONG_NM        VARCHAR(80)  NULL COMMENT '읍면동명',
  POST_NO          VARCHAR(10)  NULL COMMENT '우편번호',
  X_POS            DECIMAL(10,7) NULL COMMENT '경도(LON)',
  Y_POS            DECIMAL(10,7) NULL COMMENT '위도(LAT)',
  LOCATION         POINT         NULL COMMENT '좌표 POINT(x,y)',
  DR_TOT_CNT       INT NULL COMMENT '의사 총원',
  MDEPT_GDR_CNT    INT NULL COMMENT '전문의 수',
  MDEPT_INTN_CNT   INT NULL COMMENT '인턴 수',
  MDEPT_RESDNT_CNT INT NULL COMMENT '레지던트 수',
  MDEPT_SDR_CNT    INT NULL COMMENT '기타 의사 수',
  DETY_GDR_CNT     INT NULL COMMENT '치과의사 수',
  DETY_INTN_CNT    INT NULL COMMENT '치과 인턴 수',
  DETY_RESDNT_CNT  INT NULL COMMENT '치과 레지던트 수',
  DETY_SDR_CNT     INT NULL COMMENT '치과 기타 의사 수',
  CMDC_GDR_CNT     INT NULL COMMENT '한의사 수',
  CMDC_INTN_CNT    INT NULL COMMENT '한방 인턴 수',
  CMDC_RESDNT_CNT  INT NULL COMMENT '한방 레지던트 수',
  CMDC_SDR_CNT     INT NULL COMMENT '한방 기타 의사 수',
  PNURS_CNT        INT NULL COMMENT '간호사 수',
  ESTB_DD          CHAR(8)       NULL COMMENT '개설일자 YYYYMMDD',
  DISTANCE         DECIMAL(10,3) NULL COMMENT '거리(질의 시 계산값 저장 가능)',
  CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_HIRA_YKIHO (YKIHO) COMMENT '기관 식별자 유니크',
  KEY IDX_HIRA_NAME (YADM_NM) COMMENT '기관명 색인',
  KEY IDX_HIRA_ADDR (ADDR) COMMENT '주소 색인'
)  COMMENT='심평원 병원 기본정보';

-- ----------------------------------------------------------------------
-- NEMC_EMERGENCY_BASE: 응급의료기관 기본정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS NEMC_EMERGENCY_BASE (
  ID               BIGINT UNSIGNED NOT NULL PRIMARY KEY
                     DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  HPID             VARCHAR(16)  NOT NULL COMMENT '응급기관 ID',
  DUTY_NAME        VARCHAR(500) NULL COMMENT '기관명',
  DUTY_ADDR        VARCHAR(500) NULL COMMENT '주소',
  DUTY_TEL1        VARCHAR(30)  NULL COMMENT '대표전화',
  DUTY_TEL3        VARCHAR(30)  NULL COMMENT '응급실 전화',
  POST_CDN1        VARCHAR(5)   NULL COMMENT '우편번호 앞자리',
  POST_CDN2        VARCHAR(5)   NULL COMMENT '우편번호 뒷자리',
  WGS84_LON        DECIMAL(10,7) NULL COMMENT '경도',
  WGS84_LAT        DECIMAL(10,7) NULL COMMENT '위도',
  LOCATION         POINT         NULL COMMENT '좌표 POINT',
  DUTY_INF         TEXT          NULL COMMENT '기관 안내/소개',
  DUTY_MAPIMG      VARCHAR(500)  NULL COMMENT '지도 이미지 URL',
  DUTY_ERYN        TINYINT       NULL COMMENT '응급실 여부',
  DUTY_HAYN        TINYINT       NULL COMMENT '입원실 여부',
  DUTY_HANO        INT           NULL COMMENT '병상 수',
  HVEC INT NULL COMMENT '뇌혈관센터 가용', 
  HVOC INT NULL COMMENT '심혈관센터 가용', 
  HVCC INT NULL COMMENT '화상센터 가용', 
  HVNCC INT NULL COMMENT '신경과 가용', 
  HVCCC INT NULL COMMENT '중증소아센터 가용', 
  HVICC INT NULL COMMENT '중환자실 가용', 
  HVGC INT NULL COMMENT '외상센터 가용',
  DUTY_TIME1S CHAR(4) NULL COMMENT '월요일 진료시작', DUTY_TIME1C CHAR(4) NULL COMMENT '월요일 진료종료',
  DUTY_TIME2S CHAR(4) NULL COMMENT '화요일 시작',     DUTY_TIME2C CHAR(4) NULL COMMENT '화요일 종료',
  DUTY_TIME3S CHAR(4) NULL COMMENT '수요일 시작',     DUTY_TIME3C CHAR(4) NULL COMMENT '수요일 종료',
  DUTY_TIME4S CHAR(4) NULL COMMENT '목요일 시작',     DUTY_TIME4C CHAR(4) NULL COMMENT '목요일 종료',
  DUTY_TIME5S CHAR(4) NULL COMMENT '금요일 시작',     DUTY_TIME5C CHAR(4) NULL COMMENT '금요일 종료',
  DUTY_TIME6S CHAR(4) NULL COMMENT '토요일 시작',     DUTY_TIME6C CHAR(4) NULL COMMENT '토요일 종료',
  DUTY_TIME7S CHAR(4) NULL COMMENT '일요일 시작',     DUTY_TIME7C CHAR(4) NULL COMMENT '일요일 종료',
  DUTY_TIME8S CHAR(4) NULL COMMENT '공휴일 시작',     DUTY_TIME8C CHAR(4) NULL COMMENT '공휴일 종료',
  M_KIOSK_TY25 ENUM('Y','N') NULL COMMENT '소아응급 구분', 
  M_KIOSK_TY1  ENUM('Y','N') NULL COMMENT '뇌출혈', 
  M_KIOSK_TY2  ENUM('Y','N') NULL COMMENT '뇌경색', 
  M_KIOSK_TY3  ENUM('Y','N') NULL COMMENT '심근경색', 
  M_KIOSK_TY4  ENUM('Y','N') NULL COMMENT '중증외상', 
  M_KIOSK_TY5  ENUM('Y','N') NULL COMMENT '화상', 
  M_KIOSK_TY6  ENUM('Y','N') NULL COMMENT '정신', 
  M_KIOSK_TY7  ENUM('Y','N') NULL COMMENT '중증', 
  M_KIOSK_TY8  ENUM('Y','N') NULL COMMENT '소아', 
  M_KIOSK_TY9  ENUM('Y','N') NULL COMMENT '분만', 
  M_KIOSK_TY10 ENUM('Y','N') NULL COMMENT '고압산소', 
  M_KIOSK_TY11 ENUM('Y','N') NULL COMMENT '기타',
  DGID_ID_NAME TEXT NULL COMMENT '진료과/센터 상세',
  HPBDN INT NULL COMMENT '분만실', HPCCUYN INT NULL COMMENT '흉부외과 중환자', HPCUYN INT NULL COMMENT '중환자실', HPERYN INT NULL COMMENT '응급실', 
  HPGRYN INT NULL COMMENT '입원실', HPICUYN INT NULL COMMENT '신생아중환자', HPNICUYN INT NULL COMMENT '소아중환자', HPOPYN INT NULL COMMENT '수술실',
  HIRA_YKIHO       VARCHAR(500) NULL COMMENT '심평원 YKIHO FK',
  CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_NEMC_EM_HPID (HPID) COMMENT '응급기관 고유 ID',
  KEY IDX_NEMC_EM_NAME (DUTY_NAME) COMMENT '기관명 색인',
  KEY IDX_NEMC_EM_ADDR (DUTY_ADDR) COMMENT '주소 색인',
  KEY IDX_NEMC_EM_HIRA (HIRA_YKIHO) COMMENT '심평원 YKIHO 색인',
  CONSTRAINT FK_NEMC_EM_TO_HIRA FOREIGN KEY (HIRA_YKIHO)
    REFERENCES HIRA_HOSPITAL_INFO(YKIHO)
    ON UPDATE CASCADE ON DELETE SET NULL
)  COMMENT='응급의료기관 기본정보 (NEMC API)';

-- ----------------------------------------------------------------------
-- NEMC_TRAUMA_BASE: 외상센터 기본정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS NEMC_TRAUMA_BASE (
  ID               BIGINT UNSIGNED NOT NULL PRIMARY KEY
                     DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3))*1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  HPID             VARCHAR(16)  NOT NULL COMMENT '외상센터 ID',
  DUTY_NAME        VARCHAR(500) NULL COMMENT '센터명',
  DUTY_ADDR        VARCHAR(500) NULL COMMENT '주소',
  DUTY_TEL1        VARCHAR(30)  NULL COMMENT '대표전화',
  DUTY_TEL3        VARCHAR(30)  NULL COMMENT '응급실 전화',
  POST_CDN1        VARCHAR(5)   NULL COMMENT '우편번호 앞자리',
  POST_CDN2        VARCHAR(5)   NULL COMMENT '우편번호 뒷자리',
  WGS84_LON        DECIMAL(10,7) NULL COMMENT '경도',
  WGS84_LAT        DECIMAL(10,7) NULL COMMENT '위도',
  LOCATION         POINT         NULL COMMENT '좌표 POINT',
  DUTY_INF         TEXT          NULL COMMENT '센터 안내',
  DUTY_MAPIMG      VARCHAR(500)  NULL COMMENT '지도 이미지 URL',
  DUTY_ERYN        TINYINT       NULL COMMENT '응급실 여부',
  DUTY_HAYN        TINYINT       NULL COMMENT '입원실 여부',
  DUTY_HANO        INT           NULL COMMENT '병상 수',
  HVEC INT NULL COMMENT '뇌혈관 가용', HVOC INT NULL COMMENT '심혈관 가용', HVCC INT NULL COMMENT '화상 가용',
  HVNCC INT NULL COMMENT '신경과 가용', HVCCC INT NULL COMMENT '중증소아 가용', HVICC INT NULL COMMENT 'ICU 가용', H_VGC INT NULL COMMENT '외상센터 가용',
  DUTY_TIME1S CHAR(4) NULL COMMENT '월 시작', DUTY_TIME1C CHAR(4) NULL COMMENT '월 종료',
  DUTY_TIME2S CHAR(4) NULL COMMENT '화 시작', DUTY_TIME2C CHAR(4) NULL COMMENT '화 종료',
  DUTY_TIME3S CHAR(4) NULL COMMENT '수 시작', DUTY_TIME3C CHAR(4) NULL COMMENT '수 종료',
  DUTY_TIME4S CHAR(4) NULL COMMENT '목 시작', DUTY_TIME4C CHAR(4) NULL COMMENT '목 종료',
  DUTY_TIME5S CHAR(4) NULL COMMENT '금 시작', DUTY_TIME5C CHAR(4) NULL COMMENT '금 종료',
  DUTY_TIME6S CHAR(4) NULL COMMENT '토 시작', DUTY_TIME6C CHAR(4) NULL COMMENT '토 종료',
  DUTY_TIME7S CHAR(4) NULL COMMENT '일 시작', DUTY_TIME7C CHAR(4) NULL COMMENT '일 종료',
  DUTY_TIME8S CHAR(4) NULL COMMENT '공휴일 시작', DUTY_TIME8C CHAR(4) NULL COMMENT '공휴일 종료',
  M_KIOSK_TY25 ENUM('Y','N') NULL COMMENT '소아응급', 
  M_KIOSK_TY1  ENUM('Y','N') NULL COMMENT '뇌출혈', 
  M_KIOSK_TY2  ENUM('Y','N') NULL COMMENT '뇌경색', 
  M_KIOSK_TY3  ENUM('Y','N') NULL COMMENT '심근경색', 
  M_KIOSK_TY4  ENUM('Y','N') NULL COMMENT '중증외상', 
  M_KIOSK_TY5  ENUM('Y','N') NULL COMMENT '화상', 
  M_KIOSK_TY6  ENUM('Y','N') NULL COMMENT '정신', 
  M_KIOSK_TY7  ENUM('Y','N') NULL COMMENT '중증', 
  M_KIOSK_TY8  ENUM('Y','N') NULL COMMENT '소아', 
  M_KIOSK_TY9  ENUM('Y','N') NULL COMMENT '분만', 
  M_KIOSK_TY10 ENUM('Y','N') NULL COMMENT '고압산소', 
  M_KIOSK_TY11 ENUM('Y','N') NULL COMMENT '기타',
  DGID_ID_NAME TEXT NULL COMMENT '진료과/센터 상세',
  HPBDN INT NULL COMMENT '분만실', HPCCUYN INT NULL COMMENT '흉부외과 중환자', HPCUYN INT NULL COMMENT '중환자실', HPERYN INT NULL COMMENT '응급실', 
  HPGRYN INT NULL COMMENT '입원실', HPICUYN INT NULL COMMENT '신생아중환자', HPNICUYN INT NULL COMMENT '소아중환자', HPOPYN INT NULL COMMENT '수술실',
  HIRA_YKIHO       VARCHAR(500) NULL COMMENT '심평원 YKIHO FK',
  CREATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_NEMC_TR_HPID (HPID) COMMENT '외상센터 고유 ID',
  KEY IDX_NEMC_TR_NAME (DUTY_NAME) COMMENT '센터명 색인',
  KEY IDX_NEMC_TR_ADDR (DUTY_ADDR) COMMENT '주소 색인',
  KEY IDX_NEMC_TR_HIRA (HIRA_YKIHO) COMMENT '심평원 YKIHO 색인',
  CONSTRAINT FK_NEMC_TR_TO_HIRA FOREIGN KEY (HIRA_YKIHO)
    REFERENCES HIRA_HOSPITAL_INFO(YKIHO)
    ON UPDATE CASCADE ON DELETE SET NULL
)  COMMENT='외상센터 기본정보 (NEMC API)';

-- ----------------------------------------------------------------------
-- HIRA_PHARMACY_INFO: 약국 기본정보
-- ----------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS HIRA_PHARMACY_INFO (
  ID         BIGINT UNSIGNED NOT NULL PRIMARY KEY
               DEFAULT (UNIX_TIMESTAMP(CURRENT_TIMESTAMP(3)) * 1000) COMMENT '레코드 고유 ID(밀리초 TS)',
  YKIHO      VARCHAR(500)  NOT NULL COMMENT '요양기관 기호(암호화)',
  YADM_NM    VARCHAR(100) NOT NULL COMMENT '약국명/기관명',
  CL_CD      VARCHAR(2)   NULL COMMENT '종별코드(예: 81)',
  CL_CD_NM   VARCHAR(100) NULL COMMENT '종별 코드명',
  SIDO_CD    VARCHAR(6)   NULL COMMENT '시도코드',
  SIDO_CD_NM VARCHAR(100) NULL COMMENT '시도명',
  SGGU_CD    VARCHAR(6)   NULL COMMENT '시군구코드',
  SGGU_CD_NM VARCHAR(100) NULL COMMENT '시군구명',
  EMDONG_NM  VARCHAR(100) NULL COMMENT '읍면동명',
  POST_NO    VARCHAR(6)   NULL COMMENT '우편번호',
  ADDR       VARCHAR(500) NULL COMMENT '주소',
  TELNO      VARCHAR(50)  NULL COMMENT '전화번호',
  ESTB_DD    CHAR(8)      NULL COMMENT '개설일자(YYYYMMDD 원문)',
  X_POS      DECIMAL(16,13) NULL COMMENT '경도(LON, 소수 13)',
  Y_POS      DECIMAL(16,13) NULL COMMENT '위도(LAT, 소수 13)',
  LOCATION   POINT          NULL COMMENT '좌표 POINT(x,y)',
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  UNIQUE KEY UK_PHARM_YKIHO (YKIHO) COMMENT '약국 식별자 유니크',
  KEY IDX_PHARM_NAME (YADM_NM) COMMENT '약국명 색인',
  KEY IDX_PHARM_ADDR (ADDR) COMMENT '주소 색인'
)  COMMENT='약국 기본정보 (HIRA)';




/* =========================================================
   3) DUR 성분 기준 테이블군 — PK를 원문 일련번호(DUR_SEQ)로 통일
   (단, 성분 병용금기는 원문에 일련번호가 없어서 자연키 사용)
========================================================= */

DROP TABLE IF EXISTS DUR_MIX_CONTRAINDICATION;
-- 성분-성분 병용금기: 원문에 개별 일련번호가 없어 (INGR_CODE, MIXTURE_INGR_CODE) 복합 PK 사용
CREATE TABLE DUR_MIX_CONTRAINDICATION (
  TYPE_NAME              VARCHAR(20)   NULL  COMMENT '유형명: 병용금기',
  MIX_TYPE               VARCHAR(20)   NULL  COMMENT '혼합 유형: 단일/복합',
  INGR_CODE              VARCHAR(20)   NOT NULL COMMENT '성분 코드(대상)',
  INGR_ENG_NAME          VARCHAR(500)  NULL  COMMENT '성분명(영문)',
  INGR_KOR_NAME          VARCHAR(500)  NULL  COMMENT '성분명(한글)',
  MIX                    VARCHAR(500)  NULL  COMMENT '혼합 성분 정보(원문)',
  ORI                    TEXT          NULL  COMMENT '원문 제품/제형 목록',
  CLASS                  VARCHAR(500)  NULL  COMMENT '분류 코드/명',
  MIXTURE_MIX_TYPE       VARCHAR(20)   NULL  COMMENT '상대 혼합 유형',
  MIXTURE_INGR_CODE      VARCHAR(20)   NOT NULL COMMENT '상대 성분 코드',
  MIXTURE_INGR_ENG_NAME  VARCHAR(500)  NULL  COMMENT '상대 성분명(영문)',
  MIXTURE_INGR_KOR_NAME  VARCHAR(500)  NULL  COMMENT '상대 성분명(한글)',
  MIXTURE_MIX            VARCHAR(500)  NULL  COMMENT '상대 혼합 성분 정보',
  MIXTURE_ORI            TEXT          NULL  COMMENT '상대 원문 제품/제형 목록',
  MIXTURE_CLASS          VARCHAR(500)  NULL  COMMENT '상대 분류 코드/명',
  NOTIFICATION_DATE      CHAR(8)       NULL  COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT         TEXT          NULL  COMMENT '금기/주의 내용',
  REMARK                 VARCHAR(500)  NULL  COMMENT '비고',
  DEL_YN                 VARCHAR(10)   NULL  COMMENT '삭제 여부',
  CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (INGR_CODE, MIXTURE_INGR_CODE),               -- 자연키 기반 PK (대칭 A-B/B-A 별개 저장)
  KEY IDX_MIX_INGR (INGR_CODE),
  KEY IDX_MIX_MIXTURE (MIXTURE_INGR_CODE),
  KEY IDX_MIX_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR: 병용금기(성분 기준, 자연키 PK)';

DROP TABLE IF EXISTS DUR_PREGNANCY_CONTRAINDICATION;
CREATE TABLE DUR_PREGNANCY_CONTRAINDICATION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 임부금기',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형(쉼표 구분)',
  GRADE              VARCHAR(20)   NULL    COMMENT '금기 등급(예: 1등급)',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '금기/주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),                         -- 원문 일련번호를 PK로
  KEY IDX_PREG_INGR (INGR_CODE),
  KEY IDX_PREG_GRADE (GRADE),
  KEY IDX_PREG_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR: 임부금기(성분 기준)';

DROP TABLE IF EXISTS DUR_DOSE_CAUTION;
CREATE TABLE DUR_DOSE_CAUTION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 용량주의',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형',
  MAX_QTY            VARCHAR(100)  NULL    COMMENT '최대 허용 용량',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_DOSE_INGR (INGR_CODE),
  KEY IDX_DOSE_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR: 용량주의(성분 기준)';

DROP TABLE IF EXISTS DUR_DURATION_CAUTION;
CREATE TABLE DUR_DURATION_CAUTION (
  DUR_SEQ              BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME            VARCHAR(20)   NULL    COMMENT '유형명: 투여기간주의',
  MIX_TYPE             VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR             TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR             TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME           VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME            VARCHAR(800)  NULL    COMMENT '제형',
  MAX_DOSAGE_TERM      VARCHAR(100)  NULL    COMMENT '최대 투여기간',
  NOTIFICATION_DATE    CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT       TEXT          NULL    COMMENT '주의 내용',
  REMARK               VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN               VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_DUR_INGR (INGR_CODE),
  KEY IDX_DUR_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR: 투여기간주의(성분 기준)';

DROP TABLE IF EXISTS DUR_ELDERLY_CAUTION;
CREATE TABLE DUR_ELDERLY_CAUTION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 노인주의',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_ELDERLY_INGR (INGR_CODE),
  KEY IDX_ELDERLY_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR: 노인주의(성분 기준)';

DROP TABLE IF EXISTS DUR_AGE_CONTRAINDICATION;
CREATE TABLE DUR_AGE_CONTRAINDICATION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 특정연령대금기',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  FORM_NAME          VARCHAR(800)  NULL    COMMENT '제형',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '금기/주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  DEL_YN             VARCHAR(10)   NULL    COMMENT '삭제 여부',
  AGE_BASE           VARCHAR(50)   NULL    COMMENT '연령 기준(예: 18세 이하)',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_AGE_INGR (INGR_CODE),
  KEY IDX_AGE_DATE (NOTIFICATION_DATE),
  KEY IDX_AGE_BASE (AGE_BASE)
)  COMMENT='DUR: 특정연령대금기(성분 기준)';

DROP TABLE IF EXISTS DUR_THERAPEUTIC_DUPLICATION;
CREATE TABLE DUR_THERAPEUTIC_DUPLICATION (
  DUR_SEQ            BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  TYPE_NAME          VARCHAR(20)   NULL    COMMENT '유형명: 효능군중복',
  MIX_TYPE           VARCHAR(20)   NULL    COMMENT '혼합 유형',
  INGR_CODE          VARCHAR(20)   NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME      VARCHAR(500)  NULL    COMMENT '성분명(영문)',
  INGR_NAME          VARCHAR(500)  NULL    COMMENT '성분명(한글)',
  MIX_INGR           TEXT          NULL    COMMENT '혼합 성분 정보',
  ORI_INGR           TEXT          NULL    COMMENT '원문 성분/제품 목록',
  CLASS_NAME         VARCHAR(500)  NULL    COMMENT '분류명/효능군',
  EFFECT_CODE        VARCHAR(500)  NULL    COMMENT '효능군 코드/명',
  NOTIFICATION_DATE  CHAR(8)       NULL    COMMENT '고시일자',
  PROHBT_CONTENT     TEXT          NULL    COMMENT '금기/주의 내용',
  REMARK             VARCHAR(500)  NULL    COMMENT '비고',
  SERS_NAME          VARCHAR(500)  NULL    COMMENT '상세 계열/군 명칭',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_DUP_INGR (INGR_CODE),
  KEY IDX_DUP_EFFECT (EFFECT_CODE),
  KEY IDX_DUP_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR: 효능군중복(성분 기준)';

/* =========================================================
   4) DUR 품목 기준 테이블군 — PK: 원문 DUR_SEQ (쌍은 복합PK)
========================================================= */

DROP TABLE IF EXISTS ITEM_MIX_CONTRAINDICATION;
-- 품목 병용금기: 본/상대 행 각각 DUR_SEQ가 존재 → (DUR_SEQ, MIXTURE_DUR_SEQ) 복합 PK
CREATE TABLE ITEM_MIX_CONTRAINDICATION (
  DUR_SEQ                BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(본 행)',
  TYPE_CODE              VARCHAR(200)   NULL     COMMENT '유형 코드(예:A)',
  TYPE_NAME              VARCHAR(20)  NULL     COMMENT '유형명: 병용금기',
  MIX                    VARCHAR(20)  NULL     COMMENT '혼합 유형: 단일/복합',
  INGR_CODE              VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_KOR_NAME          VARCHAR(500) NULL     COMMENT '성분명(한글)',
  INGR_ENG_NAME          VARCHAR(500) NULL     COMMENT '성분명(영문)',
  MIX_INGR               TEXT         NULL     COMMENT '혼합 성분 정보',
  ITEM_SEQ               VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  ITEM_NAME              VARCHAR(500) NULL     COMMENT '품목명',
  ENTP_NAME              VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                  TEXT         NULL     COMMENT '성상',
  FORM_CODE              VARCHAR(20)  NULL     COMMENT '제형 코드',
  ETC_OTC_CODE           VARCHAR(20)  NULL     COMMENT '전문/일반 코드',
  CLASS_CODE             VARCHAR(20)  NULL     COMMENT '분류 코드',
  FORM_NAME              VARCHAR(800) NULL     COMMENT '제형명',
  ETC_OTC_NAME           VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  CLASS_NAME             VARCHAR(500) NULL     COMMENT '분류명',
  MAIN_INGR              VARCHAR(500) NULL     COMMENT '주성분 원문',
  MIXTURE_DUR_SEQ        BIGINT UNSIGNED NOT NULL COMMENT '상대 DUR 일련번호',
  MIXTURE_MIX            VARCHAR(20)  NULL     COMMENT '상대 혼합 유형',
  MIXTURE_INGR_CODE      VARCHAR(20)  NULL     COMMENT '상대 성분 코드',
  MIXTURE_INGR_KOR_NAME  VARCHAR(500) NULL     COMMENT '상대 성분명(한글)',
  MIXTURE_INGR_ENG_NAME  VARCHAR(500) NULL     COMMENT '상대 성분명(영문)',
  MIXTURE_ITEM_SEQ       VARCHAR(20)  NULL     COMMENT '상대 품목 기준코드',
  MIXTURE_ITEM_NAME      VARCHAR(500) NULL     COMMENT '상대 품목명',
  MIXTURE_ENTP_NAME      VARCHAR(500) NULL     COMMENT '상대 제조/수입사명',
  MIXTURE_FORM_CODE      VARCHAR(20)  NULL     COMMENT '상대 제형 코드',
  MIXTURE_ETC_OTC_CODE   VARCHAR(20)  NULL     COMMENT '상대 전문/일반 코드',
  MIXTURE_CLASS_CODE     VARCHAR(20)  NULL     COMMENT '상대 분류 코드',
  MIXTURE_FORM_NAME      VARCHAR(800) NULL     COMMENT '상대 제형명',
  MIXTURE_ETC_OTC_NAME   VARCHAR(20)  NULL     COMMENT '상대 전문/일반 구분명',
  MIXTURE_CLASS_NAME     VARCHAR(500) NULL     COMMENT '상대 분류명',
  MIXTURE_MAIN_INGR      VARCHAR(500) NULL     COMMENT '상대 주성분 원문',
  NOTIFICATION_DATE      CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT         TEXT         NULL     COMMENT '금기/주의 내용',
  REMARK                 VARCHAR(500) NULL     COMMENT '비고',
  ITEM_PERMIT_DATE       VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  MIXTURE_ITEM_PERMIT_DATE VARCHAR(20) NULL    COMMENT '상대 품목 허가일(원문)',
  MIXTURE_CHART          TEXT         NULL     COMMENT '상대 성상',
  CHANGE_DATE            VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  MIXTURE_CHANGE_DATE    VARCHAR(20)  NULL     COMMENT '상대 변경일(원문)',
  BIZRNO                 VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  CREATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT             DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ, ITEM_SEQ, MIXTURE_ITEM_SEQ),      -- 복합 PK
  KEY IDX_ITEM_MIX_ITEM (ITEM_SEQ),
  KEY IDX_ITEM_MIX_DATE (NOTIFICATION_DATE),
  KEY IDX_ITEM_MIX_MITEM (MIXTURE_ITEM_SEQ)
)  COMMENT='DUR 품목: 병용금기(복합 PK)';

DROP TABLE IF EXISTS ITEM_ELDERLY_CAUTION;
CREATE TABLE ITEM_ELDERLY_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 노인주의',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_ELDERLY_INGR (INGR_CODE),
  KEY IDX_ITEM_ELDERLY_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR 품목: 노인주의';

DROP TABLE IF EXISTS ITEM_DUR_INFO;
CREATE TABLE ITEM_DUR_INFO (
  ITEM_SEQ           VARCHAR(20)  NOT NULL COMMENT '품목 기준코드(원문 키)',
  ITEM_NAME          VARCHAR(500) NULL     COMMENT '품목명',
  ENTP_NAME          VARCHAR(500) NULL     COMMENT '제조/수입사명',
  ITEM_PERMIT_DATE   VARCHAR(100)  NULL     COMMENT '품목 허가일(원문)',
  ETC_OTC_CODE       VARCHAR(20)  NULL     COMMENT '전문/일반 코드 또는 명',
  CLASS_NO           VARCHAR(60)  NULL     COMMENT '분류번호(예: [222]진해거담제)',
  CHART              TEXT         NULL     COMMENT '성상',
  BAR_CODE           VARCHAR(50)  NULL     COMMENT '바코드',
  MATERIAL_NAME      TEXT         NULL     COMMENT '원료성분/규격',
  EE_DOC_ID          VARCHAR(500) NULL     COMMENT '효능효과 문서 링크',
  UD_DOC_ID          VARCHAR(500) NULL     COMMENT '용법용량 문서 링크',
  NB_DOC_ID          VARCHAR(500) NULL     COMMENT '주의사항 문서 링크',
  INSERT_FILE        VARCHAR(500) NULL     COMMENT '첨부문서 링크',
  STORAGE_METHOD     TEXT         NULL     COMMENT '보관방법',
  VALID_TERM         VARCHAR(100) NULL     COMMENT '유효기간',
  REEXAM_TARGET      VARCHAR(100) NULL     COMMENT '재심사 대상',
  REEXAM_DATE        VARCHAR(100)  NULL     COMMENT '재심사 기간/일자(원문)',
  PACK_UNIT          VARCHAR(2000) NULL     COMMENT '포장단위',
  EDI_CODE           VARCHAR(50)  NULL     COMMENT 'EDI 코드',
  CANCEL_DATE        VARCHAR(20)  NULL     COMMENT '허가취소일(원문)',
  CANCEL_NAME        VARCHAR(20)  NULL     COMMENT '허가상태(정상/취소 등)',
  TYPE_CODE          VARCHAR(200)   NULL     COMMENT 'DUR 유형 코드',
  TYPE_NAME          VARCHAR(20)  NULL     COMMENT 'DUR 유형명',
  CHANGE_DATE        VARCHAR(100)  NULL     COMMENT '변경일(원문)',
  BIZRNO             VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  CREATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),                         -- 메타는 ITEM_SEQ가 자연키
  KEY IDX_ITEM_DUR_CHANGE (CHANGE_DATE)
)  COMMENT='DUR 품목 메타정보(ITEM_SEQ PK)';

DROP TABLE IF EXISTS ITEM_AGE_CONTRAINDICATION;
CREATE TABLE ITEM_AGE_CONTRAINDICATION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 특정연령대금기',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '금기/주의 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_AGE_INGR (INGR_CODE),
  KEY IDX_ITEM_AGE_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR 품목: 특정연령대금기';

DROP TABLE IF EXISTS ITEM_DOSE_CAUTION;
CREATE TABLE ITEM_DOSE_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 용량주의',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용(최대 허용량 등)',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_DOSE_INGR (INGR_CODE),
  KEY IDX_ITEM_DOSE_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR 품목: 용량주의';

DROP TABLE IF EXISTS ITEM_DURATION_CAUTION;
CREATE TABLE ITEM_DURATION_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 투여기간주의',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용(최대 투여기간 등)',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_DUR_INGR (INGR_CODE),
  KEY IDX_ITEM_DUR_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR 품목: 투여기간주의';

DROP TABLE IF EXISTS ITEM_THERAPEUTIC_DUPLICATION;
CREATE TABLE ITEM_THERAPEUTIC_DUPLICATION (
  DUR_SEQ              BIGINT UNSIGNED NOT NULL COMMENT 'DUR 일련번호(원문 키)',
  EFFECT_NAME          VARCHAR(500) NULL     COMMENT '효능군명',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 효능군중복',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  FORM_CODE_NAME       VARCHAR(500) NULL     COMMENT '제형 코드명',
  MIX                  VARCHAR(20)  NULL     COMMENT '혼합 유형',
  MIX_INGR             TEXT         NULL     COMMENT '혼합 성분 정보',
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  CHART                TEXT         NULL     COMMENT '성상',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  FORM_CODE            VARCHAR(20)  NULL     COMMENT '제형 코드',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ETC_OTC_CODE         VARCHAR(20)  NULL     COMMENT '전문/일반 코드',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '금기/주의 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  BIZRNO               VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  SERS_NAME            VARCHAR(500) NULL     COMMENT '상세 계열/군 명칭',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (DUR_SEQ),
  KEY IDX_ITEM_TD_ITEM (ITEM_SEQ),
  KEY IDX_ITEM_TD_INGR (INGR_CODE),
  KEY IDX_ITEM_TD_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR 품목: 효능군중복';

DROP TABLE IF EXISTS ITEM_SUSTAINED_RELEASE_SPLIT_CAUTION;
CREATE TABLE ITEM_SUSTAINED_RELEASE_SPLIT_CAUTION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 분할주의',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(100)  NULL     COMMENT '품목 허가일(원문, 예: 1971May6th)',
  FORM_CODE_NAME       VARCHAR(500) NULL     COMMENT '제형 코드명(예: 장용성필름코팅정)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MIX                  VARCHAR(20)  NULL     COMMENT '혼합 유형: 복합/단일',
  MAIN_INGR            VARCHAR(700) NULL     COMMENT '주성분 원문(복합 가능)',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '주의 내용(예: 분할불가)',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  BIZRNO               VARCHAR(20)  NULL     COMMENT '사업자등록번호',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_SR_CHANGE (CHANGE_DATE)
)  COMMENT='DUR 품목: 서방정 분할주의';

DROP TABLE IF EXISTS ITEM_PREGNANCY_CONTRAINDICATION;
CREATE TABLE ITEM_PREGNANCY_CONTRAINDICATION (
  ITEM_SEQ             VARCHAR(20)  NOT NULL COMMENT '품목 기준코드',
  TYPE_NAME            VARCHAR(20)  NULL     COMMENT '유형명: 임부금기',
  MIX_TYPE             VARCHAR(20)  NULL     COMMENT '혼합 유형',
  INGR_CODE            VARCHAR(20)  NOT NULL COMMENT '성분 코드',
  INGR_ENG_NAME        VARCHAR(500) NULL     COMMENT '성분명(영문)',
  INGR_NAME            VARCHAR(500) NULL     COMMENT '성분명(한글)',
  MIX_INGR             VARCHAR(500) NULL     COMMENT '혼합 성분 정보',
  FORM_NAME            VARCHAR(800) NULL     COMMENT '제형명',
  ITEM_NAME            VARCHAR(500) NULL     COMMENT '품목명',
  ITEM_PERMIT_DATE     VARCHAR(20)  NULL     COMMENT '품목 허가일(원문)',
  ENTP_NAME            VARCHAR(500) NULL     COMMENT '제조/수입사명',
  CHART                TEXT         NULL     COMMENT '성상',
  CLASS_CODE           VARCHAR(20)  NULL     COMMENT '분류 코드',
  CLASS_NAME           VARCHAR(500) NULL     COMMENT '분류명',
  ETC_OTC_NAME         VARCHAR(20)  NULL     COMMENT '전문/일반 구분명',
  MAIN_INGR            VARCHAR(500) NULL     COMMENT '주성분 원문',
  NOTIFICATION_DATE    CHAR(8)      NULL     COMMENT '고시일자 YYYYMMDD',
  PROHBT_CONTENT       TEXT         NULL     COMMENT '금기 내용',
  REMARK               VARCHAR(500) NULL     COMMENT '비고',
  INGR_ENG_NAME_FULL   VARCHAR(500) NULL     COMMENT '성분명(영문+국문)',
  CHANGE_DATE          VARCHAR(20)  NULL     COMMENT '변경일(원문)',
  CREATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '생성시각',
  UPDATED_AT           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '수정시각',
  PRIMARY KEY (ITEM_SEQ),
  KEY IDX_ITEM_PREG_INGR (INGR_CODE),
  KEY IDX_ITEM_PREG_DATE (NOTIFICATION_DATE)
)  COMMENT='DUR 품목: 임부금기';



/* =========================================================
   LLM RAG 기반 증상 분석을 위한 테이블 수정
========================================================= */

-- SYMPTOM_LOGS 테이블에 LLM 관련 컬럼 추가
ALTER TABLE SYMPTOM_LOGS
  ADD COLUMN IF NOT EXISTS MEDICAL_TERMS TEXT NULL COMMENT 'LLM이 변환한 의학 용어들 (JSON 배열)',
  ADD COLUMN IF NOT EXISTS SUSPECTED_DISEASES JSON NULL COMMENT 'LLM이 추론한 의심 질병 목록 (JSON 배열)',
  ADD COLUMN IF NOT EXISTS LLM_ANALYSIS TEXT NULL COMMENT 'LLM의 전체 분석 내용',
  ADD COLUMN IF NOT EXISTS SEVERITY_SCORE INT NULL COMMENT '심각도 점수 (1-10, 높을수록 심각)',
  ADD COLUMN IF NOT EXISTS RECOMMENDED_DRUGS JSON NULL COMMENT '추천 약품 목록 (JSON 배열)',
  ADD COLUMN IF NOT EXISTS NEARBY_PHARMACIES JSON NULL COMMENT '주변 약국 정보 (JSON)',
  ADD COLUMN IF NOT EXISTS NEARBY_HOSPITALS JSON NULL COMMENT '주변 병원 정보 (JSON)',
  MODIFY COLUMN ITEM_SEQ VARCHAR(20) NULL COMMENT '품목 기준코드(DUR)',
  MODIFY COLUMN PREDICTED_DISEASE VARCHAR(500) NULL COMMENT 'LLM이 추정한 질병명';

-- 인덱스 추가
CREATE INDEX IF NOT EXISTS IDX_LOGS_SEVERITY ON SYMPTOM_LOGS (SEVERITY_SCORE, CREATED_AT);

-- 참고: ETC_OTC_CODE 값
-- '01' = 전문의약품
-- '02' = 일반의약품 (OTC)








